#lang racket/base
(require racket/list racket/set "mesh3d.rkt" "mesh-topology3d.rkt" "polyhedral-complex3d.rkt" "vec3.rkt")
(provide (struct-out net-hinge3d) (struct-out net-face-transform3d)
         (struct-out polyhedron-net3d) prepare-polyhedron-net3d)

(struct net-hinge3d (parent child primal-edge) #:transparent)
;; An explicit rigid local frame: a source point p maps to origin + dot(p-a,e)E
;; + dot(p-a,f)F + dot(p-a,n)N. Face points have zero final normal coordinate.
(struct net-face-transform3d (face source-origin source-e source-f source-n target-origin target-e target-f target-n) #:transparent)
(struct polyhedron-net3d (root-face hinge-tree cut-edges face-transforms flat-polygons overlaps diagnostics) #:transparent)

(define (prepare-polyhedron-net3d complex #:root-face [root 0] #:hinges [hinges #f]
                                  #:strategy [strategy 'breadth-first] #:search-limit [limit 1000])
 (unless (polyhedral-complex3d? complex) (raise-argument-error 'prepare-polyhedron-net3d "polyhedral-complex3d?" complex))
 (unless (memq strategy '(breadth-first depth-first minimum-overlap)) (raise-argument-error 'prepare-polyhedron-net3d "net strategy" strategy))
 (define faces (polyhedral-complex3d-faces complex)) (define n (vector-length faces))
 (unless (and (exact-nonnegative-integer? root) (< root n)) (raise-argument-error 'prepare-polyhedron-net3d "face index" root))
 (for ([f (in-vector faces)]) (unless (polyhedral-face3d-boundary-vertex-indices f) (raise-arguments-error 'prepare-polyhedron-net3d "simple polygonal faces" "face" f)))
 (define topology (polyhedral-complex3d-topology complex))
 (define adj (make-vector n '()))
 (for ([i (in-range (vector-length (mesh-topology3d-edges topology)))])
  (define fs (vector-ref (polyhedral-complex3d-edge-to-faces complex) i))
  (when (= (vector-length fs) 2) (define a (vector-ref fs 0)) (define b (vector-ref fs 1))
   (vector-set! adj a (cons (cons b i) (vector-ref adj a))) (vector-set! adj b (cons (cons a i) (vector-ref adj b)))))
 (define selected (and hinges (list->set hinges)))
 (define tree
  (let loop ([todo (list root)] [seen (list root)] [out '()])
   (if (null? todo) (reverse out)
    (let* ([p (car todo)] [ns (sort (filter (lambda (x) (or (not selected) (set-member? selected (cdr x)))) (vector-ref adj p)) < #:key cdr)])
     (define add (filter (lambda (x) (not (member (car x) seen))) ns))
     (loop (if (eq? strategy 'depth-first) (append (reverse (map car add)) (cdr todo)) (append (cdr todo) (map car add)))
           (append seen (map car add)) (append (for/list ([x (in-list add)]) (net-hinge3d p (car x) (cdr x))) out))))))
 (unless (= (length tree) (sub1 n)) (raise-arguments-error 'prepare-polyhedron-net3d "a connected face-adjacency spanning tree" "root" root))
 (define tree-edges (map net-hinge3d-primal-edge tree))
 (define cuts (for/vector ([i (in-range (vector-length (mesh-topology3d-edges topology)))] #:when (and (= (vector-length (vector-ref (polyhedral-complex3d-edge-to-faces complex) i)) 2) (not (member i tree-edges)))) i))
 (define vertices (mesh3d-vertices (polyhedral-complex3d-mesh complex)))
 (define root-face (vector-ref faces root)) (define rn (polyhedral-face3d-normal root-face))
 (define maps (make-vector n #f))
 (define (make-map face origin target-a target-b)
  (define bs (polyhedral-face3d-boundary-vertex-indices face)) (define a (vector-ref bs 0)) (define b (vector-ref bs 1))
  (define se (vec3-normalize (vec3- (vector-ref vertices b) (vector-ref vertices a)))) (define sn (polyhedral-face3d-normal face)) (define sf (vec3-cross sn se))
  (define te (vec3-normalize (vec3- target-b target-a))) (define tf (vec3-cross rn te))
  (net-face-transform3d #f (vector-ref vertices a) se sf sn target-a te tf rn))
 (define rb (vector-ref (polyhedral-face3d-boundary-vertex-indices root-face) 1))
 (vector-set! maps root (make-map root-face #f (vector-ref vertices (vector-ref (polyhedral-face3d-boundary-vertex-indices root-face) 0)) (vector-ref vertices rb)))
 (define (apply-map m p) (define d (vec3- p (net-face-transform3d-source-origin m))) (vec3+ (net-face-transform3d-target-origin m) (vec3+ (vec3-scale (vec3-dot d (net-face-transform3d-source-e m)) (net-face-transform3d-target-e m)) (vec3+ (vec3-scale (vec3-dot d (net-face-transform3d-source-f m)) (net-face-transform3d-target-f m)) (vec3-scale (vec3-dot d (net-face-transform3d-source-n m)) (net-face-transform3d-target-n m))))))
 (for ([h (in-list tree)])
  (define edge (mesh-edge-topology3d-vertices (vector-ref (mesh-topology3d-edges topology) (net-hinge3d-primal-edge h))))
  (define parent-map (vector-ref maps (net-hinge3d-parent h))) (define a (vector-ref edge 0)) (define b (vector-ref edge 1))
  (define child-face (vector-ref faces (net-hinge3d-child h)))
  (vector-set! maps (net-hinge3d-child h) (make-map child-face #f (apply-map parent-map (vector-ref vertices a)) (apply-map parent-map (vector-ref vertices b)))))
 (define frozen (for/vector ([m (in-vector maps)] [i (in-naturals)]) (struct-copy net-face-transform3d m [face i])))
 (define polygons (for/vector ([f (in-vector faces)] [m (in-vector frozen)]) (for/vector ([i (in-vector (polyhedral-face3d-boundary-vertex-indices f))]) (apply-map m (vector-ref vertices i)))))
 (polyhedron-net3d root (list->vector tree) (vector->immutable-vector cuts) (vector->immutable-vector frozen) (vector->immutable-vector polygons) #() (hasheq 'strategy strategy 'search-complete? (not (eq? strategy 'minimum-overlap)) 'search-limit limit)))
