#lang racket/base
(require racket/class racket/list rackunit
         (only-in pict pict->bitmap)
         "../private/data.rkt" "../private/sample.rkt")
(provide code? find-leaf pixel-bytes max-pixel-difference sample-signature)
(define (code? expected)
  (lambda (e) (and (exn:fail:slides? e) (eq? expected (exn:fail:slides-code e)))))
(define (find-leaf frame path)
  (or (findf (lambda (l) (equal? path (frame-leaf-path l))) (frame-value-leaves frame))
      (error 'find-leaf "missing ~s" path)))
(define (pixel-bytes picture)
  (define bm (pict->bitmap picture))
  (define bytes (make-bytes (* 4 (send bm get-width) (send bm get-height))))
  (send bm get-argb-pixels 0 0 (send bm get-width) (send bm get-height) bytes)
  bytes)
(define (max-pixel-difference a b)
  (unless (= (bytes-length a) (bytes-length b)) (error 'max-pixel-difference "different sizes"))
  (for/fold ([m 0]) ([x (in-bytes a)] [y (in-bytes b)]) (max m (abs (- x y)))))
(define (sample-signature frame)
  (list (frame-value-format frame) (frame-value-background frame) (frame-value-slots frame)
        (for/list ([l (in-list (frame-value-leaves frame))])
          (list (frame-leaf-path l) (frame-leaf-box l) (frame-leaf-time l)
                (frame-leaf-opacity l) (frame-leaf-scale l) (frame-leaf-clip l)
                (asset-identity (frame-leaf-asset l))))))
