#lang racket/base
;; Read example text, never execute it while building the manual.
(require racket/file racket/string racket/runtime-path scribble/manual)
(provide example-source example-part)
(define-runtime-path examples-directory "../examples")
(define (source-text name)
  (unless (and (string? name) (regexp-match? #px"^[a-z][a-z0-9-]*\\.rkt$" name))
    (raise-argument-error 'example-source "simple example filename" name))
  (file->string (build-path examples-directory name)))
(define (without-markers text)
  (string-join
   (filter (lambda (line) (not (regexp-match? #px"^;; doc: " line)))
           (string-split text "\n" #:trim? #f)) "\n"))
(define (example-source name)
  (filebox (tt (string-append "scribblings/examples/" name))
           (verbatim (without-markers (source-text name)))))
(define (example-part name part)
  (unless (and (string? part) (regexp-match? #px"^[a-z][a-z0-9-]*$" part))
    (raise-argument-error 'example-part "simple part name" part))
  (define before (string-append ";; doc: " part " begin\n"))
  (define after (string-append ";; doc: " part " end"))
  (define pieces (string-split (source-text name) before #:trim? #f))
  (unless (= (length pieces) 2)
    (raise-arguments-error 'example-part "one named example region" "file" name "part" part))
  (define tails (string-split (cadr pieces) after #:trim? #f))
  (unless (= (length tails) 2)
    (raise-arguments-error 'example-part "one closing example marker" "file" name "part" part))
  (verbatim (string-trim (car tails))))
