#lang racket/base
;; Data only. A recipe is (key source exported-scene times teaching-note).
(provide learning-example-files learning-frame-recipes)
(define learning-example-files
  '("objects-and-groups.rkt" "timing-and-visibility.rkt" "first-function-graph.rkt"))
(define learning-frame-recipes
  '(("one-moves" "objects-and-groups.rkt" one-moves (0 1 2)
      "Only the circle moves; the square stays where it was.")
    ("group-moves" "objects-and-groups.rkt" group-moves (0 1 2)
      "The whole group moves. The distance between its children stays fixed.")
    ("child-moves" "objects-and-groups.rkt" child-moves (0 1 2)
      "The circle moves in its parent's coordinates. The square stays fixed.")
    ("together" "timing-and-visibility.rkt" together (0 1/2 1 3/2 2)
      "Both objects start and finish together.")
    ("in-order" "timing-and-visibility.rkt" in-order (0 1/2 1 3/2 2)
      "The circle finishes before the square starts.")
    ("overlapping" "timing-and-visibility.rkt" overlapping (0 1/2 5/4 2 5/2)
      "The square waits half a second. Each movement lasts two seconds.")
    ("eased" "timing-and-visibility.rkt" eased (0 1/2 1 3/2 2)
      "Equal time steps cover less distance near the start and finish.")
    ("appearing" "timing-and-visibility.rkt" appearing (0 1/2 1)
      "The circle is introduced by fading in.")
    ("invisible" "timing-and-visibility.rkt" invisible (0 1/2 1)
      "At the last frame the circle is invisible but its ID is still present.")
    ("removed" "timing-and-visibility.rkt" removed (0 1/2 1)
      "At the last frame the circle is absent. The pixels alone cannot tell these cases apart.")
    ("draw-graph" "first-function-graph.rkt" drawing (0 1/2 1 3/2 2)
      "The stored curve is revealed from left to right; the function is not evaluated per frame.")
    ("move-graph" "first-function-graph.rkt" moving-diagram (0 1 2)
      "The axes and curve travel together because they belong to one group.")))
