#lang scribble/manual
@title[#:tag "part-reference" #:style '(toc grouper)]{Reference}

Look up a name, argument, result, or restriction here. The Scene API is divided
by task; it is no longer a single chapter called Quick Start. That short
introduction is now at @secref["guide-getting-started"].

The API definitions and their links are retained. Detailed model rules are in
@secref["model"], after the common Scene and animation operations.
@local-table-of-contents[]
@include-section["reference/find-a-task.scrbl"]
@include-section["reference/module-boundaries.scrbl"]
@include-section["reference/scene.scrbl"]
@include-section["reference/scene-state.scrbl"]
@include-section["reference/animation-requests.scrbl"]
@include-section["reference/native-model.scrbl"]
@include-section["reference/visuals-and-relations.scrbl"]
@include-section["reference/geometry-and-plots.scrbl"]
@include-section["reference/coordinate-decorations.scrbl"]
@include-section["reference/markers-scatter-and-areas.scrbl"]
@include-section["reference/statistical-diagrams.scrbl"]
@include-section["reference/calculus.scrbl"]
@include-section["reference/colors.scrbl"]
@include-section["reference/slides.scrbl"]
@include-section["reference/slide-tools.scrbl"]
@include-section["reference/authoring.scrbl"]
@include-section["reference/preview.scrbl"]
@include-section["reference/preview-workbench.scrbl"]
@include-section["reference/project.scrbl"]
@include-section["reference/project-workflow.scrbl"]
@include-section["reference/rendering.scrbl"]
@include-section["reference/3d-algebra.scrbl"]
@include-section["reference/ref3d-spatial-visuals-and-paths.scrbl"]
@include-section["reference/ref3d-cameras-and-projection.scrbl"]
@include-section["reference/ref3d-spatial-viewports.scrbl"]
@include-section["reference/ref3d-spatial-animation-453b89a.scrbl"]
@include-section["reference/ref3d-spatial-animation-847149f.scrbl"]
@include-section["reference/ref3d-cuts-caps-and-sec-ba40cdc.scrbl"]
@include-section["reference/ref3d-supplementary-q-t-api.scrbl"]
@include-section["reference/ref3d-supplementary-q-t-29da1c8.scrbl"]
@include-section["reference/ref3d-vectors.scrbl"]
@include-section["reference/ref3d-linear-maps-and-rotations.scrbl"]
@include-section["reference/ref3d-affine-and-decomp-37fab23.scrbl"]
@include-section["reference/ref3d-bounds-rays-and-planes.scrbl"]
@include-section["reference/ref3d-spatial-maps-and-891ec29.scrbl"]
@include-section["reference/ref3d-materials-and-lights.scrbl"]
@include-section["reference/ref3d-materials-and-lig-33bbf37.scrbl"]
@include-section["reference/ref3d-materials-and-lig-6d02ef2.scrbl"]
@include-section["reference/ref3d-materials-and-lig-bcce52f.scrbl"]
@include-section["reference/ref3d-materials-and-lig-78e41df.scrbl"]
@include-section["reference/ref3d-materials-and-lig-836167a.scrbl"]
@include-section["reference/ref3d-semantic-spatial-15dcc60.scrbl"]
@include-section["reference/ref3d-semantic-spatial-d97c90c.scrbl"]
@include-section["reference/ref3d-textured-billboards.scrbl"]
@include-section["reference/ref3d-spatial-curves-an-44fde38.scrbl"]
@include-section["reference/ref3d-spatial-anchors-a-adb8ffb.scrbl"]
@include-section["reference/ref3d-supplementary-q-t-9fe5d66.scrbl"]
@include-section["reference/ref3d-parametric-surfac-075e668.scrbl"]
@include-section["reference/ref3d-adaptive-trimmed-7c83022.scrbl"]
@include-section["reference/ref3d-constructive-solids.scrbl"]
@include-section["reference/ref3d-supplementary-q-t-100c1a0.scrbl"]
@include-section["reference/ref3d-meshes.scrbl"]
@include-section["reference/ref3d-meshes-navigable-5d87e57.scrbl"]
@include-section["reference/ref3d-meshes-polygonal-da981bf.scrbl"]
@include-section["reference/ref3d-meshes-determinis-b37f679.scrbl"]
@include-section["reference/ref3d-meshes-polyhedral-duals.scrbl"]
@include-section["reference/ref3d-meshes-schlegel-d-6fdb2d3.scrbl"]
@include-section["reference/ref3d-meshes-conservati-fc6b09c.scrbl"]
@include-section["reference/ref3d-meshes-topology-s-dbebcef.scrbl"]
@include-section["reference/ref3d-meshes-topology-d-b4e0919.scrbl"]
@include-section["reference/ref3d-clipping-sections-ae6e276.scrbl"]
@include-section["reference/ref3d-prepared-spatial-85dc26c.scrbl"]
@include-section["reference/ref3d-prepared-spatial-ff19077.scrbl"]
@include-section["reference/ref3d-prepared-spatial-fb6ff44.scrbl"]
@include-section["reference/ref3d-prepared-spatial-e990084.scrbl"]
@include-section["reference/ref3d-prepared-spatial-ac9c8db.scrbl"]
@include-section["reference/ref3d-prepared-spatial-4876728.scrbl"]
@include-section["reference/ref3d-prepared-spatial-dc0c904.scrbl"]
@include-section["reference/ref3d-prepared-spatial-250ce4a.scrbl"]
@include-section["reference/ref3d-supplementary-q-t-3c0e1ed.scrbl"]
@include-section["reference/ref3d-spatial-inspectio-46dec95.scrbl"]
@include-section["reference/ref3d-retained-renderer-65f0695.scrbl"]
@include-section["reference/ref3d-retained-renderer-0e201a5.scrbl"]
@include-section["reference/ref3d-retained-renderer-1c18112.scrbl"]
@include-section["reference/ref3d-retained-renderer-6058743.scrbl"]
@include-section["reference/ref3d-optional-racket-o-35de9ff.scrbl"]
@include-section["reference/experimental.scrbl"]
@include-section["guide/package-source.scrbl"]
