#lang racket/base
;; Explicit genuine frame rendering. No TeX, GUI, FFmpeg, or generated artwork.
(require racket/class racket/cmdline racket/file racket/list racket/path
         racket/runtime-path file/sha1 json
         (only-in pict pict->bitmap)
         animate "private/learning-catalog.rkt")
(define-runtime-path examples "examples")
(define-runtime-path installed "figures/learning-r4")
(define-runtime-path recipe-source "private/learning-catalog.rkt")
(define-runtime-path renderer-source "render-learning-illustrations.rkt")
(define schema "animate-manual-learning-frames-v1")
(define width 640)
(define height 360)
(define (checksum file) (call-with-input-file file sha1))
(define (sources)
  (for/hasheq ([name (in-list learning-example-files)])
    (values (string->symbol name) (checksum (build-path examples name)))))
;; Compare JSON fields without depending on a hash table's comparison mode.
(define (same-inputs? prior current)
  (and (hash? prior)
       (let ([old-sources (hash-ref prior 'sources #f)]
             [new-sources (hash-ref current 'sources)])
         (and (hash? old-sources)
              (= (hash-count old-sources) (hash-count new-sources))
              (for/and ([(key value) (in-hash new-sources)])
                (equal? value (hash-ref old-sources key #f)))))
       (equal? (hash-ref prior 'recipe-sha1 #f) (hash-ref current 'recipe-sha1))
       (equal? (hash-ref prior 'renderer-sha1 #f) (hash-ref current 'renderer-sha1))))
(define (pixels bm)
  (define bytes (make-bytes (* 4 (send bm get-width) (send bm get-height))))
  (send bm get-argb-pixels 0 0 (send bm get-width) (send bm get-height) bytes)
  bytes)
(define (picture sc time)
  (define old (scene-camera-at sc time))
  (scene-state->pict (scene-sample sc time)
    #:camera (make-camera #:width width #:height height
                          #:world-width (camera-world-width old)
                          #:center (camera-center old))))
(module+ main
  (define install? #f)
  (define output #f)
  (command-line #:program "render-learning-illustrations.rkt"
    #:once-each
    [("--install") "Install the figures used by Scribble" (set! install? #t)]
    #:args ([directory #f]) (set! output directory))
  (when (and install? output)
    (raise-user-error 'render-learning-illustrations "use --install or a directory, not both"))
  (define target (if install? installed
                     (path->complete-path (or output "slides-output/learning-figures"))))
  (when (link-exists? target)
    (raise-user-error 'render-learning-illustrations "refusing a symbolic-link destination"))
  (define stamp
    (hasheq 'sources (sources) 'recipe-sha1 (checksum recipe-source)
            'renderer-sha1 (checksum renderer-source)))
  (when (or (file-exists? target) (directory-exists? target))
    (define manifest (build-path target "manifest.json"))
    (unless (and install? (file-exists? manifest))
      (raise-user-error 'render-learning-illustrations "use a fresh destination: ~a" target))
    (define prior (call-with-input-file manifest read-json))
    (unless (and (equal? (hash-ref prior 'schema #f) schema)
                 (same-inputs? (hash-ref prior 'inputs #f) stamp))
      (raise-user-error 'render-learning-illustrations
        "Stored figures have changed inputs. Rename ~a to keep it as a backup, then rerun --install." target))
    (for* ([strip (in-hash-values (hash-ref prior 'strips))]
           [frame (in-list (hash-ref strip 'frames))])
      (define name (hash-ref frame 'file))
      (unless (regexp-match? #px"^[a-z0-9-]+\\.png$" name)
        (raise-user-error 'render-learning-illustrations "unsafe stored frame name"))
      (define file (build-path target name))
      (unless (and (file-exists? file) (equal? (checksum file) (hash-ref frame 'sha1)))
        (raise-user-error 'render-learning-illustrations "missing or modified stored frame: ~a" file)))
    (printf "Learning figures are already installed and verified: ~a\n" target)
    (exit 0))
  (define parent (path-only target))
  (make-directory* parent)
  (define stage (make-temporary-file ".learning-frames-~a" 'directory parent))
  (dynamic-wind
   void
   (lambda ()
     (define strips
       (for/hash ([recipe (in-list learning-frame-recipes)])
         (define key (list-ref recipe 0))
         (define source (list-ref recipe 1))
         (define binding (list-ref recipe 2))
         (define sc (dynamic-require (build-path examples source) binding))
         (define frames
           (for/list ([time (in-list (list-ref recipe 3))] [i (in-naturals)])
             (define bm (pict->bitmap (picture sc time) 'smoothed))
             (unless (bytes=? (pixels bm) (pixels (pict->bitmap (picture sc time) 'smoothed)))
               (raise-user-error 'render-learning-illustrations "nonrepeatable frame: ~a at ~a" key time))
             (define name (format "~a-~a.png" key i))
             (define path (build-path stage name))
             (unless (send bm save-file path 'png)
               (raise-user-error 'render-learning-illustrations "could not save ~a" path))
             (hasheq 'file name 'time (exact->inexact time) 'exact-time (format "~a" time)
                     'caption (format "t = ~a s" time)
                     'width (send bm get-width) 'height (send bm get-height)
                     'sha1 (checksum path))))
         (printf "~a: ~a real frames, each sampled twice\n" key (length frames))
         (values (string->symbol key)
                 (hasheq 'source source 'binding (symbol->string binding)
                         'note (list-ref recipe 4) 'frames frames))))
     (call-with-output-file (build-path stage "manifest.json")
       (lambda (out)
         (write-json (hasheq 'schema schema 'inputs stamp 'racket (version)
                             'platform (format "~a" (system-type)) 'strips strips) out)))
     (rename-file-or-directory stage target)
     (printf "Installed learning figures: ~a\n" target))
   (lambda () (when (directory-exists? stage) (delete-directory/files stage)))))
