#lang scribble/manual

@(require (for-label racket/base
                     racket/contract
                     racket/math
                     animate
                     animate/3d
                     animate/3d/render
                     animate/3d/opengl
                     animate/project))

@title[#:tag "ref3d-meshes-polyhedral-duals"]{3D: Polyhedral duals}

@declare-exporting[animate/3d #:use-sources (animate/3d)]

@seclink["3d-algebra"]{3D reference map} · @seclink["guide-3d-picture"]{First 3D picture}


@defstruct*[dual-polyhedron-face3d
            ([index exact-nonnegative-integer?]
             [primal-vertex exact-nonnegative-integer?]
             [triangle-indices vector?] [boundary-vertex-indices vector?])
            #:transparent]{A mathematical dual polygon generated by one primal
vertex. Its render-triangle indexes refer to the mesh in the enclosing result.}
@defstruct*[dual-polyhedron3d-result
            ([mesh mesh3d?] [primal-face->dual-vertex vector?]
             [primal-edge->dual-edge vector?]
             [primal-vertex->dual-face vector?] [diagnostics hash?])
            #:transparent]{An immutable dual mesh and explicit primal-to-dual
correspondence. A @racket[#f] edge mapping denotes a render diagonal inside one
grouped primal polygonal face, which has no mathematical dual edge. Diagnostics
contain @racket['rejected-render-faces] for polygonal cycles that are preserved
as topology but cannot be safely triangulated for rendering.}
@defproc[(combinatorial-dual3d [complex polyhedral-complex3d?]
                                [#:id id symbol? 'combinatorial-dual])
         dual-polyhedron3d-result?]{Creates one dual vertex at each primal
polygonal-face centroid and one dual polygon at each primal vertex. It is a
combinatorial/diagram embedding; no convexity or regularity claim is made.}
@defproc[(polar-dual3d [complex polyhedral-complex3d?]
                        [#:center center vec3? origin3]
                        [#:scale scale positive-real? 1]
                        [#:tolerance tolerance nonnegative-real? 1e-9]
                        [#:id id symbol? 'polar-dual])
         dual-polyhedron3d-result?]{Creates the polar dual. For every outward
primal face plane @math{n \cdot (x-c)=d}, its dual vertex is
@math{c + (s/d)n}. The operation rejects nonmanifold, open, nonorientable,
nonplanar, nonconvex, or centre-touching input rather than returning a false
polar dual.}

@bold{Limitations.} Duals currently require simple planar U-2 faces and a
closed orientable manifold. The combinatorial centroid embedding may overlap or
self-intersect for a nonconvex polyhedron; its exact polygonal cycle is still
returned, but unsafe projected cycles are omitted from the render mesh and
reported in diagnostics. The polar operation has
no automatic centre-finding or nonconvex repair policy.

