#lang scribble/manual

@(require (for-label racket/base
                     racket/contract
                     racket/math
                     animate
                     animate/3d
                     animate/3d/render
                     animate/3d/opengl
                     animate/project))

@title[#:tag "ref3d-meshes-topology-d-b4e0919"]{3D: Checking and repairing mesh orientation}

@declare-exporting[animate/3d #:use-sources (animate/3d)]

@seclink["3d-algebra"]{3D reference map} · @seclink["guide-3d-picture"]{First 3D picture}


@defstruct*[mesh3d-duplicate-triangle
            ([first-triangle-index exact-nonnegative-integer?]
             [duplicate-triangle-index exact-nonnegative-integer?]
             [winding (or/c 'same 'reversed)]) #:transparent]{
Records a later triangle that has the same three indexed vertices as an earlier
one, independent of cyclic rotation.}

@defstruct*[mesh3d-analysis
            ([vertex-count exact-nonnegative-integer?]
             [triangle-count exact-nonnegative-integer?]
             [edge-count exact-nonnegative-integer?]
             [degenerate-triangles vector?]
             [duplicate-triangles vector?]
             [boundary-edges vector?]
             [boundary-loops vector?]
             [nonmanifold-edges vector?]
             [inconsistent-winding-edges vector?]
             [connected-components vector?]
             [isolated-vertices vector?]
             [signed-component-volumes vector?]
             [watertight? boolean?]
             [orientable? boolean?]
             [consistently-wound? boolean?]) #:transparent]{
An immutable, deterministic report over indexed geometry. Edge records retain
first-triangle encounter order; components and loops retain source-index order.
Degeneracy uses a tolerance proportional to the mesh's squared extent rather
than one universal world-coordinate epsilon.}

@defproc[(analyze-mesh3d [mesh mesh3d?]) mesh3d-analysis?]{Computes topology
and geometric diagnostics without changing @racket[mesh].}
@defproc[(mesh3d-validate [mesh mesh3d?]) mesh3d-analysis?]{An explicit alias
for @racket[analyze-mesh3d]. Mesh construction remains cheap and does not
implicitly run this potentially expensive analysis.}
@defstruct*[mesh3d-orientation-report
            ([initial-analysis mesh3d-analysis?]
             [final-analysis mesh3d-analysis?]
             [flipped-triangle-indices vector?]
             [outward? boolean?]) #:transparent]{An immutable explanation of
an explicit orientation repair. Per-vertex normals are authored attributes and
are not silently regenerated by repair.}
@defproc[(mesh3d-orient-consistently [mesh mesh3d?])
         (values mesh3d? mesh3d-orientation-report?)]{
Returns a replacement mesh with each manifold adjacent pair oppositely wound,
or raises for degenerate, non-manifold, or parity-conflicting input.}
@defproc[(mesh3d-orient-outward [mesh mesh3d?])
         (values mesh3d? mesh3d-orientation-report?)]{
Additionally makes every closed, orientable, nonzero-volume component
outward-facing. Open, non-manifold, non-orientable, and zero-volume components
fail explicitly because they have no unambiguous outside.}
@defproc[(mesh3d-self-intersection-candidates [mesh mesh3d?]) vector?]{Returns
deterministic pairs of non-adjacent faces whose local AABBs overlap. This is a
broad-phase candidate query, not a narrow-phase proof of intersection.}

