#lang racket/base
(require racket/list "data.rkt" "check.rkt")
(provide layout layout? layout-id layout-slots layout-ref layout-names
         slot-spec slot-spec? slot-spec-name slot-spec-required? slot-spec-role
         region hbox vbox)

(define (slot-spec name #:required? [required? #f] #:role [role 'body])
  (check-id 'slot-spec name) (check-id 'slot-spec role)
  (unless (boolean? required?) (raise-argument-error 'slot-spec "boolean?" required?))
  (slot-spec-value name required? role))
(define slot-spec? slot-spec-value?)
(define slot-spec-name slot-spec-value-name)
(define slot-spec-required? slot-spec-value-required?)
(define slot-spec-role slot-spec-value-role)
(define (make-node kind name children basis grow gap align valign padding minimum maximum)
  (unless (or (eq? basis 'content) (nonnegative-number? basis))
    (raise-argument-error kind "nonnegative basis or 'content" basis))
  (check-number kind grow)
  (unless (or (symbol? gap) (nonnegative-number? gap)) (raise-argument-error kind "gap token or nonnegative real" gap))
  (check-enum kind align '(left center right))
  (check-enum kind valign '(top center bottom))
  (check-number kind padding) (check-number kind minimum)
  (unless (and (or (eqv? maximum +inf.0) (nonnegative-number? maximum)) (>= maximum minimum))
    (raise-argument-error kind "maximum >= minimum" maximum))
  (unless (and (list? children) (andmap layout-node? children))
    (raise-argument-error kind "layout nodes" children))
  (layout-node kind name children basis grow gap align valign padding minimum maximum))
(define (region name #:basis [basis 0] #:grow [grow 0] #:align [align 'left]
                #:valign [valign 'top] #:padding [padding 0] #:min [minimum 0] #:max [maximum +inf.0])
  (check-id 'region name)
  (make-node 'region name '() basis grow 0 align valign padding minimum maximum))
(define (hbox #:basis [basis 0] #:grow [grow 0] #:gap [gap 'column-gap]
              #:padding [padding 0] #:min [minimum 0] #:max [maximum +inf.0] . children)
  (make-node 'hbox #f children basis grow gap 'left 'top padding minimum maximum))
(define (vbox #:basis [basis 0] #:grow [grow 0] #:gap [gap 'section-gap]
              #:padding [padding 0] #:min [minimum 0] #:max [maximum +inf.0] . children)
  (make-node 'vbox #f children basis grow gap 'left 'top padding minimum maximum))
(define (region-names node)
  (if (eq? (layout-node-kind node) 'region) (list (layout-node-name node))
      (append-map region-names (layout-node-children node))))
(define (layout #:id id #:slots slots #:arrange arrange
                #:standard [standard #f] #:portrait [portrait #f] #:fallback [fallback #f])
  (check-id 'layout id)
  (unless (layout-node? arrange)
    (raise-argument-error 'layout "layout node as #:arrange" arrange))
  (unless (and (list? slots) (andmap slot-spec? slots))
    (raise-argument-error 'layout "list of slot-spec?" slots))
  (unique! 'layout (map slot-spec-name slots))
  (when (memq 'footer (map slot-spec-name slots))
    (slides-error 'reserved-slot '(footer) "footer is shared slide chrome, not a custom layout region"))
  (for ([node (in-list (filter values (list arrange standard portrait)))])
    (unless (layout-node? node) (raise-argument-error 'layout "layout node" node))
    (define names (region-names node))
    (unique! 'layout-regions names)
    (unless (equal? (sort names symbol<?) (sort (map slot-spec-name slots) symbol<?))
      (slides-error 'layout-regions (list id) "each layout variant must contain every declared region exactly once")))
  (unless (or (not fallback) (eq? fallback 'wide))
    (raise-argument-error 'layout "#f or 'wide as fallback" fallback))
  (layout-value id slots arrange standard portrait fallback))
(define layout? layout-value?)
(define layout-id layout-value-id)
(define layout-slots layout-value-slots)
(define (spec name role [required? #t]) (slot-spec name #:role role #:required? required?))
(define catalogue
  (list
   (cons 'title (list (spec 'title 'title) (spec 'subtitle 'subtitle #f)))
   (cons 'section (list (spec 'title 'section-heading) (spec 'subtitle 'subtitle #f)))
   (cons 'title+body (list (spec 'title 'title) (spec 'body 'body)))
   (cons 'title+two-column (list (spec 'title 'title) (spec 'left 'body) (spec 'right 'body)))
   (cons 'title+figure (list (spec 'title 'title) (spec 'body 'body #f) (spec 'figure 'body)))
   (cons 'figure+caption (list (spec 'figure 'body) (spec 'caption 'caption #f)))
   (cons 'figure-full (list (spec 'figure 'body)))
   (cons 'equation-focus (list (spec 'equation 'title) (spec 'annotation 'annotation #f)))
   (cons 'equation+explanation (list (spec 'title 'title #f) (spec 'equation 'title) (spec 'body 'body)))
   (cons 'theorem (list (spec 'title 'title) (spec 'statement 'quotation) (spec 'body 'body #f)))
   (cons 'quote (list (spec 'quote 'quotation) (spec 'attribution 'caption #f)))
   (cons 'blank (list (spec 'content 'body #f)))))
(define (layout-names) (map car catalogue))
(define (layout-ref name)
  (cond [(layout-value? name) name]
        [(assq name catalogue)
         => (lambda (entry) (layout-value name (cdr entry) 'builtin 'builtin 'builtin 'wide))]
        [else (slides-error 'unknown-layout (list name) "unknown layout")]))
