#lang racket/base
(require racket/list racket/match "data.rkt" "check.rkt" "appearance.rkt" "layout.rkt"
         (only-in "../../colors.rkt" color-spec? color-spec->datum datum->color-spec))
(provide make-slide slide? slide-id slide-layout slide-slots slide-appearance slide-notes slide-ref
         make-slot slot-content paragraph-content pict-content image-content/proc make-bullets
         build-slide hold-slide slide-clip? slide-clip-slide beat beat? beat-name
         make-narration narration? reveal-slot conceal-slot emphasize-slot replace-content play-content
         storyboard storyboard? storyboard-id storyboard-theme storyboard-format storyboard-motion storyboard-subtitles? storyboard-shot storyboard-cut slide-transition
         slide-transition? slide-transition-effect slide-transition-duration slide-transition-keys
         slide-transition-direction slide-transition-easing slide-transition-scale slide-transition-color slide-transition-depth
         storyboard-ref storyboard-with-theme storyboard-with-format check-storyboard
         slide-action? content? bound-source)

(define (content? x) (or (string? x) (content-value? x)))
(define (paragraph-content text #:role [role #f] #:align [align #f])
  (unless (string? text) (raise-argument-error 'paragraph-content "string?" text))
  (when role (check-id 'paragraph-content role))
  (when align (check-enum 'paragraph-content align '(left center right)))
  (content-value 'text (string->immutable-string text) (hash 'role role 'align align)))
(define (pict-content value #:fit [fit 'contain])
  (check-enum 'pict-content fit '(contain cover natural))
  (content-value 'pict value (hash 'fit fit)))
(define (image-content/proc source #:fit [fit 'contain] #:asset-base [base #f])
  (unless (path-string? source) (raise-argument-error 'image-content "path-string?" source))
  (check-enum 'image-content fit '(contain cover natural))
  (content-value 'image (immutable-copy source) (hash 'fit fit 'asset-base base)))
(define (make-bullets entries #:ordered? [ordered? #f])
  (unless (and (list? entries) (andmap pair? entries))
    (raise-argument-error 'make-bullets "list of (cons symbol content)" entries))
  (for ([e (in-list entries)]) (check-id 'make-bullets (car e)))
  (unique! 'bullets (map car entries))
  (unless (boolean? ordered?) (raise-argument-error 'make-bullets "boolean?" ordered?))
  (content-value 'bullets (immutable-copy entries) (hash 'ordered? ordered?)))
(define (make-slot value #:key [key #f] #:align [align #f] #:valign [valign #f] #:fit [fit #f])
  (when key (check-id 'slide key))
  (when align (check-enum 'slide align '(left center right)))
  (when valign (check-enum 'slide valign '(top center bottom)))
  (when fit (check-enum 'slide fit '(contain cover natural)))
  (slot-value (immutable-copy value) key align valign fit))
(define (make-slide #:id [id 'slide] #:layout [chosen-layout 'blank]
                    #:slots [slots (hash)] #:theme [theme #f] #:notes [notes ""])
  (check-id 'make-slide id)
  (define l (layout-ref chosen-layout))
  (unless (or (not theme) (slide-theme? theme))
    (raise-argument-error 'make-slide "slide-theme? or #f" theme))
  (unless (string? notes) (raise-argument-error 'make-slide "string? as notes" notes))
  (define entries (if (hash? slots) (hash->list slots) slots))
  (unless (and (list? entries) (andmap pair? entries))
    (raise-argument-error 'make-slide "hash or association list of slots" slots))
  (for ([entry (in-list entries)]) (check-id 'make-slide (car entry)))
  (unique! 'slide-slots (map car entries))
  (define table
    (for/hash ([entry (in-list entries)])
      (values (car entry) (if (slot-value? (cdr entry)) (cdr entry) (make-slot (cdr entry))))))
  (define names (cons 'footer (map slot-spec-name (layout-slots l))))
  (for ([name (in-hash-keys table)])
    (unless (memq name names) (slides-error 'unknown-slot (list id name) "slot is not declared by this layout")))
  (for ([spec (in-list (layout-slots l))] #:when (slot-spec-required? spec))
    (unless (hash-has-key? table (slot-spec-name spec))
      (slides-error 'missing-slot (list id (slot-spec-name spec)) "required slot is missing")))
  (unique! 'continuity-keys (filter values (map slot-value-key (hash-values table))))
  (slide-value id l table theme (string->immutable-string notes)))
;; Programmatic counterpart of slot options accepted by the slide macro.
(define slot-content make-slot)
(define slide? slide-value?)
(define slide-id slide-value-id)
(define slide-layout slide-value-layout)
(define slide-slots slide-value-slots)
(define slide-appearance slide-value-theme)
(define slide-notes slide-value-notes)
(define (slide-ref s name)
  (slot-value-content (hash-ref (slide-value-slots s) name
                               (lambda () (slides-error 'unknown-slot (list name) "unknown slide slot")))))
(define (make-narration text #:audio [audio #f] #:draft-duration [draft #f]
                        #:at [at 0] #:source-start [source-start 0] #:duration [duration #f]
                        #:captions [captions #f] #:asset-base [base #f])
  (unless (string? text) (raise-argument-error 'narration "string?" text))
  (unless (or (and audio (not draft)) (and draft (not audio)))
    (slides-error 'narration-source '() "narration needs exactly one audio source or draft duration"))
  (when audio (unless (path-string? audio) (raise-argument-error 'narration "audio path" audio)))
  (when draft (check-number 'narration draft #t))
  (check-number 'narration at) (check-number 'narration source-start)
  (when duration (check-number 'narration duration #t))
  (when (and draft (or duration (> source-start 0)))
    (slides-error 'draft-trim '() "source trimming applies only to recorded narration"))
  (when captions
    (unless (and (list? captions)
                 (andmap (lambda (c) (match c [(list a b (? string?)) (and (nonnegative-number? a) (positive-number? b) (< a b))] [_ #f])) captions))
      (raise-argument-error 'narration "caption segments (list start end text)" captions))
    (for ([a (in-list captions)] [b (in-list (if (null? captions) '() (cdr captions)))])
      (when (> (cadr a) (car b)) (slides-error 'caption-overlap '() "caption segments must be ordered and nonoverlapping"))))
  (narration-value (string->immutable-string text) (immutable-copy audio) draft at source-start duration (immutable-copy captions) base))
(define narration? narration-value?)
(define (action kind target at duration effect payload options)
  (define path (selector-path target))
  (check-number kind at)
  (when duration (check-number kind duration))
  (action-value kind path at duration effect (immutable-copy payload) options))
(define (reveal-slot target #:at [at 0] #:duration [duration 0.4] #:effect [effect 'fade])
  (check-enum 'reveal-slot effect '(fade instant))
  (action 'reveal target at duration effect #f (hash)))
(define (conceal-slot target #:at [at 0] #:duration [duration 0.4] #:effect [effect 'fade])
  (check-enum 'conceal-slot effect '(fade instant))
  (action 'conceal target at duration effect #f (hash)))
(define (emphasize-slot target #:at [at 0] #:duration [duration 0.8] #:scale [scale 1.08])
  (check-number 'emphasize-slot scale #t)
  (action 'emphasize target at duration 'pulse scale (hash)))
(define (replace-content target content #:at [at 0] #:duration [duration 0.4] #:effect [effect 'crossfade])
  (unless (= (length (selector-path target)) 1)
    (slides-error 'replacement-target (selector-path target) "replace-content targets a complete slot"))
  (check-enum 'replace-content effect '(crossfade instant))
  (action 'replace target at duration effect content (hash)))
(define (play-content target #:at [at 0] #:from [from #f] #:to [to 'end]
                      #:duration [duration #f] #:retime [retime #f])
  (unless (= (length (selector-path target)) 1)
    (slides-error 'play-target (selector-path target) "play-content targets a complete animated slot"))
  (unless (or (not retime) (eq? retime 'stretch))
    (raise-argument-error 'play-content "#f or 'stretch as #:retime" retime))
  (action 'play target at duration 'linear to (hash 'from from 'retime retime)))
(define slide-action? action-value?)
(define (beat name #:duration [duration #f] #:narration [narration #f] #:tail-hold [tail 0] . actions)
  (check-id 'beat name)
  (when duration (check-number 'beat duration #t))
  (check-number 'beat tail)
  (unless (or (not narration) (narration-value? narration)) (raise-argument-error 'beat "narration?" narration))
  (unless (or duration narration) (slides-error 'beat-duration (list name) "a beat without narration needs an explicit duration"))
  (unless (andmap action-value? actions) (raise-argument-error 'beat "slide actions" actions))
  (beat-value name duration narration tail actions))
(define beat? beat-value?)
(define beat-name beat-value-name)
(define (build-slide s #:initial [initial 'visible] #:poster [poster 'end]
                     #:motion [motion #f] . beats)
  (unless (slide? s) (raise-argument-error 'build-slide "slide?" s))
  (unless (or (memq initial '(visible hidden)) (list? initial))
    (raise-argument-error 'build-slide "'visible, 'hidden, or selectors" initial))
  (when (list? initial) (for-each selector-path initial))
  (when motion (check-enum 'build-slide motion '(normal reduced)))
  (unless (andmap beat? beats) (raise-argument-error 'build-slide "beats" beats))
  (unique! 'beats (map beat-name beats))
  (clip-value s (immutable-copy initial) (immutable-copy poster) motion beats #f))
(define (hold-slide s #:duration duration)
  (struct-copy clip-value (build-slide s (beat 'hold #:duration duration)) [hold? #t]))
(define slide-clip? clip-value?)
(define slide-clip-slide clip-value-slide)
(define (storyboard-shot id clip)
  (check-id 'storyboard-shot id)
  (unless (clip-value? clip)
    (raise-argument-error 'storyboard-shot "slide clip; use hold-slide for a static slide" clip))
  (shot-value id clip))
(define slide-transition? transition-value?)
(define slide-transition-effect transition-value-effect)
(define slide-transition-duration transition-value-duration)
(define slide-transition-keys transition-value-keys)
(define slide-transition-direction transition-value-direction)
(define slide-transition-easing transition-value-easing)
(define slide-transition-scale transition-value-scale)
(define slide-transition-color transition-value-color)
(define slide-transition-depth transition-value-depth)

;; A cut is a separate, zero-duration boundary. Every animated bridge reserves
;; its own strictly positive interval and freezes the two local content clocks.
(define (storyboard-cut) (transition-value 'cut 0 '() #f 'linear #f #f 'slot))
(define (slide-transition #:effect [effect 'crossfade]
                          #:duration [duration 0.6]
                          #:keys [keys '()]
                          #:direction [direction #f]
                          #:easing [easing 'linear]
                          #:scale [scale #f]
                          #:color [color #f]
                          #:depth [depth #f])
  (check-enum 'slide-transition effect
              '(crossfade match push wipe cover uncover zoom fade-through))
  (check-number 'slide-transition duration #t)
  (check-enum 'slide-transition easing '(linear smooth ease-in ease-out ease-in-out))
  (unless (list? keys) (raise-argument-error 'slide-transition "list of continuity keys" keys))
  (for-each (lambda (k) (check-id 'slide-transition k)) keys)
  (unique! 'slide-transition keys)
  (when (and (not (eq? effect 'match)) (pair? keys))
    (slides-error 'transition-keys '() "continuity keys require #:effect 'match"))
  (when depth
    (check-enum 'slide-transition depth '(auto slot semantic))
    (unless (eq? effect 'match)
      (slides-error 'transition-option '() "#:depth applies only to match")))
  (define directional? (memq effect '(push wipe cover uncover)))
  (when direction
    (check-enum 'slide-transition direction '(left right up down))
    (unless directional?
      (slides-error 'transition-option '() "#:direction applies only to push, wipe, cover, or uncover")))
  (when scale
    (unless (and (positive-number? scale) (< scale 1))
      (raise-argument-error 'slide-transition "finite real strictly between 0 and 1 as #:scale" scale))
    (unless (eq? effect 'zoom)
      (slides-error 'transition-option '() "#:scale applies only to zoom")))
  (when color
    (unless (color-spec? color) (raise-argument-error 'slide-transition "color-spec? as #:color" color))
    (unless (eq? effect 'fade-through)
      (slides-error 'transition-option '() "#:color applies only to fade-through")))
  (transition-value effect duration keys
                    (and directional? (or direction 'left)) easing
                    (and (eq? effect 'zoom) (or scale 0.85))
                    (and (eq? effect 'fade-through)
                         (datum->color-spec (color-spec->datum (or color "#000000"))))
                    (if (eq? effect 'match) (or depth 'auto) 'slot)))
(define (storyboard #:id [id 'storyboard] #:theme [theme lecture-light]
                    #:format [format widescreen] #:motion [motion 'normal]
                    #:subtitles? [subtitles? #t] . entries)
  (check-id 'storyboard id)
  (unless (slide-theme? theme) (raise-argument-error 'storyboard "slide-theme?" theme))
  (unless (slide-format? format) (raise-argument-error 'storyboard "slide-format?" format))
  (check-enum 'storyboard motion '(normal reduced))
  (unless (boolean? subtitles?) (raise-argument-error 'storyboard "boolean?" subtitles?))
  (unless (and (pair? entries) (shot-value? (car entries)) (shot-value? (last entries)))
    (slides-error 'storyboard-structure (list id) "storyboard must begin and end with a shot"))
  (for ([entry (in-list entries)])
    (unless (or (shot-value? entry) (transition-value? entry))
      (raise-argument-error 'storyboard "shot or transition" entry)))
  (for ([a (in-list entries)] [b (in-list (cdr entries))])
    (when (and (transition-value? a) (transition-value? b))
      (slides-error 'storyboard-structure (list id) "consecutive transitions are invalid")))
  (unique! 'shots (map shot-value-id (filter shot-value? entries)))
  (storyboard-value id theme format motion subtitles? entries))
(define storyboard? storyboard-value?)
(define storyboard-id storyboard-value-id)
(define storyboard-theme storyboard-value-theme)
(define storyboard-format storyboard-value-format)
(define storyboard-motion storyboard-value-motion)
(define storyboard-subtitles? storyboard-value-subtitles?)
(define (storyboard-with-theme b theme)
  (unless (slide-theme? theme) (raise-argument-error 'storyboard-with-theme "slide-theme?" theme))
  (struct-copy storyboard-value b [theme theme]))
(define (storyboard-with-format b format)
  (unless (slide-format? format) (raise-argument-error 'storyboard-with-format "slide-format?" format))
  (struct-copy storyboard-value b [format format]))
(define (bound-source b source)
  (define reserve?
    (and (storyboard-value-subtitles? b)
         (for/or ([shot (in-list (filter shot-value? (storyboard-value-entries b)))])
           (define clip (shot-value-clip shot))
           (or (ormap beat-value-narration (clip-value-beats clip))
               (let ([contents
                      (append (map slot-value-content (hash-values (slide-value-slots (clip-value-slide clip))))
                              (for*/list ([beat (in-list (clip-value-beats clip))]
                                          [action (in-list (beat-value-actions beat))]
                                          #:when (eq? (action-value-kind action) 'replace))
                                (action-value-payload action)))])
                 (for/or ([content (in-list contents)])
                   (and (content-value? content)
                        (eq? (hash-ref (content-value-options content) 'media #f) 'import))))))))
  (contextual-value source (storyboard-value-theme b) (storyboard-value-format b)
                    (if reserve? (theme-spacing (storyboard-value-theme b) 'subtitle-height) 0)
                    (storyboard-value-motion b)))
(define (storyboard-ref b id)
  (cond [(prepared-storyboard-value? b)
         (define shot (findf (lambda (s) (eq? id (prepared-shot-id s))) (prepared-storyboard-value-shots b)))
         (if shot (prepared-shot-clip shot) (slides-error 'unknown-shot (list id) "unknown shot"))]
        [(storyboard-value? b)
         (define shot (findf (lambda (s) (and (shot-value? s) (eq? id (shot-value-id s)))) (storyboard-value-entries b)))
         (if shot (bound-source b (shot-value-clip shot)) (slides-error 'unknown-shot (list id) "unknown shot"))]
        [else (raise-argument-error 'storyboard-ref "storyboard or prepared storyboard" b)]))
(define (check-storyboard b)
  (cond [(prepared-storyboard-value? b) (prepared-storyboard-value-diagnostics b)]
        [(storyboard-value? b)
         (list (diagnostic 'info 'preparation-pending (list (storyboard-value-id b))
                           "Declarations are valid; measure layout and media with prepare-storyboard!." (hash)))]
        [else (raise-argument-error 'check-storyboard "storyboard or prepared storyboard" b)]))
