#lang racket/base
(require (for-syntax racket/base racket/list racket/path)
         "model.rkt")
(provide slide bullets narration image-content)

(begin-for-syntax
  (define (split-options who stx xs)
    (let loop ([rest xs] [options '()])
      (cond [(and (pair? rest) (keyword? (syntax-e (car rest))))
             (unless (pair? (cdr rest)) (raise-syntax-error who "missing keyword value" stx (car rest)))
             (loop (cddr rest) (append options (list (car rest) (cadr rest))))]
            [else (values options rest)])))
  (define (parse-slot who stx clause)
    (define xs (syntax->list clause))
    (unless (and xs (pair? xs) (identifier? (car xs)))
      (raise-syntax-error who "expected [slot-name options ... content]" stx clause))
    (define-values (options rest) (split-options who stx (cdr xs)))
    (unless (= (length rest) 1) (raise-syntax-error who "one content expression is required" stx clause))
    #`(cons '#,(syntax-e (car xs)) (make-slot #,(car rest) #,@options)))
  (define (source-base stx)
    (define source (syntax-source stx))
    (and (path-string? source)
         (complete-path? source)
         (let ([base (path-only source)]) (and base (path->string base)))))
  (define (has-keyword? xs key) (ormap (lambda (x) (eq? (syntax-e x) key)) xs)))

(define-syntax (slide stx)
  (syntax-case stx ()
    [(_ . body)
     (let ()
       (define xs (syntax->list #'body))
       (unless xs (raise-syntax-error 'slide "expected keyword options and slot clauses" stx))
       (define-values (options clauses) (split-options 'slide stx xs))
       (when (has-keyword? options '#:slots)
         (raise-syntax-error 'slide "use make-slide for a computed #:slots table" stx))
       #`(make-slide #,@options #:slots
                     (list #,@(map (lambda (c) (parse-slot 'slide stx c)) clauses))))]))
(define-syntax (bullets stx)
  (syntax-case stx ()
    [(_ . body)
     (let ()
       (define-values (options clauses) (split-options 'bullets stx (syntax->list #'body)))
       (define entries
         (for/list ([clause (in-list clauses)])
           (define xs (syntax->list clause))
           (unless (and xs (= (length xs) 2) (identifier? (car xs)))
             (raise-syntax-error 'bullets "expected [item-name content]" stx clause))
           #`(cons '#,(syntax-e (car xs)) #,(cadr xs))))
       #`(make-bullets (list #,@entries) #,@options))]))
(define-syntax (narration stx)
  (syntax-case stx ()
    [(_ . body)
     (let ([xs (syntax->list #'body)])
       (if (has-keyword? xs '#:asset-base)
           #`(make-narration #,@xs)
           #`(make-narration #,@xs #:asset-base '#,(source-base stx))))]))
(define-syntax (image-content stx)
  (syntax-case stx ()
    [(_ . body)
     (let ([xs (syntax->list #'body)])
       (if (has-keyword? xs '#:asset-base)
           #`(image-content/proc #,@xs)
           #`(image-content/proc #,@xs #:asset-base '#,(source-base stx))))]))
