#lang racket/base

;; Regression checks motivated by the user's 2026-09-12 native review bundles.
;; Racket base only: no mock of Animate or native typography. Pixel integration
;; is covered separately by audit-render-test.rkt on a complete installation.
(require racket/list racket/runtime-path racket/string
         "../core.rkt" "../review-plan.rkt" "../private/compiler.rkt"
         "../private/narration.rkt" "../examples/private/review-example-names.rkt"
         (prefix-in c: "../constructions.rkt"))
(provide audit-check-groups run-audit-checks)
(define-runtime-path examples "../examples")
(define total (make-parameter #f))
(define current-name (make-parameter "audit"))
(define (check value message . args)
  (when (total) (set-box! (total) (add1 (unbox (total)))))
  (unless value (error 'audit-check "~a: ~a ~e" (current-name) message args)))
(define (near a b [eps 1e-8]) (check (< (abs (- a b)) eps) "numeric mismatch" a b))
(define (fails thunk)
  (check (with-handlers ([exn:fail:geometry? (lambda (e) #t)]) (thunk) #f) "expected diagnostic"))
(define (program body [helpers (hash)])
  (make-construction-program 'audit body helpers "audit-checks.rkt"))
(define (build name [mode 'light])
  ((dynamic-require (build-path examples (string-append name ".rkt")) 'make-demo-timeline) #:theme-mode mode))
(define (p-of t) (geometry-realization-program (geometry-timeline-realization t)))
(define (v-of t) (geometry-realization-values (geometry-timeline-realization t)))
(define (shown t id)
  (define p (hash-ref (geometry-timeline-final t) id #f))
  (and p (presentation-shown? p)))
(define (captions t) (filter values (map geometry-step-span-narration (geometry-timeline-steps t))))
(define (marker-counts t)
  (define-values (masks labels) (geometry-visibility-masks t))
  (allocate-marker-counts (geometry-program-nodes (p-of t)) (v-of t) masks))
(define (marker-count t id) (hash-ref (marker-counts t) id))
(define (top-steps t)
  (filter (lambda (s) (= (length (geometry-step-span-path s)) 1)) (geometry-timeline-steps t)))

(define-construction joined
  (given [A : Point] [B : Point]) (results Segment)
  (step (caption "Join " A " to " B ".") [s (segment A B)]) (result s))
(define-construction nested
  (given [A : Point] [B : Point]) (results Segment)
  (step (caption "Construct " s ".") (expand [s (joined A B)])) (result s))
(construction named
  (given [P (point 0 0)] [Q (point 2 0)])
  (layout (label-text P "A′") (label-text Q "B′") (label-text result "A′B′"))
  (step "Outer." (expand [result (nested P Q)])))

(define basic-groups
 (list
  (cons "caption references survive two levels of helper substitution"
    (lambda ()
      (define t (construction->timeline named))
      (check (member "Join A′ to B′." (captions t)) "wrong helper input names" (captions t))
      (check (member "Construct A′B′." (captions t)) "wrong helper result name")
      (check (andmap string? (captions t)) "unresolved caption template")))
  (cons "literal captions remain literal and a template may name a new binding"
    (lambda ()
      (define t (construction->timeline
        (program '((given [P (point 0 0)] [Q (point 2 0)])
                   (step "Keep A and B literally." [s (segment P Q)])
                   (step (caption "Let " M " be the midpoint.") [M (midpoint P Q)])))))
      (check (equal? (captions t) '("Keep A and B literally." "Let M be the midpoint.")) "caption text changed")))
  (cons "bad or nondrawable caption references fail at elaboration"
    (lambda ()
      (for ([caption '((caption "Missing " Z) (caption 12) (caption "Number " N))])
        (fails (lambda () (program `((given [P (point 0 0)] [N 2]) (step ,caption))))))))
  (cons "fit-circle includes the whole primary circle but does not widen all helper circles"
    (lambda ()
      (define plain (program '((given [O (point 0 0)] [P (point 2 0)]) (step [k (circle O P)]))))
      (define fit (program '((given [O (point 0 0)] [P (point 2 0)])
                            (layout (fit-circle k)) (step [k (circle O P)]))))
      (define r (realize-construction fit))
      (for ([p (list (point -2 0) (point 2 0) (point 0 -2) (point 0 2))])
        (check (point-in-view? p (geometry-realization-view r) 0.45) "primary circle cropped"))
      (check (> (geometry-view-width (geometry-realization-view r))
                (geometry-view-width (geometry-realization-view (realize-construction plain)))) "opt-in has no effect")
      (fails (lambda () (program '((given [P (point 0 0)]) (layout (fit-circle P))))))))
  (cons "a radius-only circle's arbitrary eastward origin is not a layout anchor"
    (lambda ()
      (define r (realize-construction
        (program '((given [O (point 0 0)] [P (point 0 2)]) (step [k (circle O #:radius 100)])))))
      (check (not (member (point 100 0) (realization-anchor-points r))) "synthetic anchor changed the view")
      (check (< (geometry-view-width (geometry-realization-view r)) 10) "helper radius controls camera")))
  (cons "angle identity uses rays, not endpoint distances or point ordering"
    (lambda ()
      (define t (construction->timeline
        (program '((given [O (point 0 0)] [A (point 2 0)] [B (point 0 3)]
                          [X (point 6 0)] [Y (point 0 9)]
                          [P (point 5 0)] [Q (point 7 0)] [R (point 5 3)])
                   (step [a (marker (angle A O B))])
                   (step [e (marker (equal-angle (angle Y O X) (angle Q P R)))])
                   (step [b (marker (angle Q P R))])))))
      (check (= (marker-count t 'a) (marker-count t 'e) (marker-count t 'b)) "same angle has different arcs")))
  (cons "isolated single-angle indicators do not reserve extra equality classes"
    (lambda ()
      (define t (build "copy-angle"))
      (check (= (marker-count t 'source-mark) 1 (marker-count t 'target-mark)) "alpha arcs differ")))
  (cons "copy-angle shows a real chord and keeps the arbitrary opening interior"
    (lambda ()
      (define t (build "copy-angle"))
      (define env (v-of t))
      (define chord-node
        (findf (lambda (n) (string-suffix? (symbol->string (geometry-node-id n)) "/chord")) (geometry-program-nodes (p-of t))))
      (check chord-node "source chord missing")
      (define chord (hash-ref env (geometry-node-id chord-node)))
      (check (> (distance (segment-a chord) (hash-ref env 'B)) 0.05) "opening degenerate")
      (check (< (distance (segment-a chord) (hash-ref env 'B)) (distance (hash-ref env 'A) (hash-ref env 'B))) "opening not interior")
      (check (> (distance (segment-b chord) (hash-ref env 'C)) 0.1) "helper point still collides with C")
      (check (for/or ([s (geometry-timeline-steps t)])
               (and (geometry-step-span-narration s)
                    (regexp-match? #rx"form a chord" (geometry-step-span-narration s))
                    (presentation-shown? (hash-ref (geometry-step-span-after s) (geometry-node-id chord-node)))))
             "chord not visible when explained")))
  (cons "expanded erect-perpendicular uses unique names, never a second public A or B"
    (lambda ()
      (define t (build "square-on-segment"))
      (define nodes (geometry-program-nodes (p-of t)))
      (define-values (visible labels) (geometry-visibility-masks t))
      (for ([n nodes] #:when (and (hash-has-key? labels (geometry-node-id n))
                                  (not (geometry-node-public? n))
                                  (regexp-match? #rx"/(A|B)$" (symbol->string (geometry-node-id n)))
                                  (equal? (geometry-node-type n) 'Point)))
        (define val (hash-ref (v-of t) (geometry-node-id n)))
        (unless (or (equal? val (hash-ref (v-of t) 'A)) (equal? val (hash-ref (v-of t) 'B)))
          (check (not (member (annotation-text (p-of t) (geometry-node-id n)) '("A" "B"))) "private point reused public name")))
      (check (for/or ([s (captions t)]) (regexp-match? #rx"Choose A₁" s)) "resolved selection caption missing")))
  (cons "final incircle and orthocenter display all three right-angle markers"
    (lambda ()
      (for ([name '("incircle" "orthocenter")])
        (define t (build name))
        (check (= 3 (for/sum ([(id v) (in-hash (v-of t))] #:when (and (perpendicular-marker? v) (shown t id))) 1))
               "missing right-angle markers" name))))
  (cons "the distance example shows the unit, equal lengths and both right angles"
    (lambda ()
      (define t (build "parallel-at-distance"))
      (check (equal? (annotation-text (p-of t) 'unit) "d") "unit has no name")
      (check (= 2 (for/sum ([(id v) (in-hash (v-of t))] #:when (and (perpendicular-marker? v) (shown t id))) 1)) "missing second right angle")))
  (cons "the regular hexagon retains the comparison radius in the final figure"
    (lambda ()
      (define t (build "regular-hexagon"))
      (check (shown t 'OA) "radius hidden while caption compares lengths")
      (define s (hash-ref (v-of t) 'sides))
      (check (= (length (equal-length-marker-segments s)) 7) "radius absent from equality marks")
      (check (shown t 'AB) "first hexagon side missing")))
  (cons "gallery includes simultaneous one/two/three arc classes and removes the earlier bisector"
    (lambda ()
      (define t (build "gallery"))
      (define counts (marker-counts t))
      (check (equal? (map (lambda (id) (hash-ref counts id)) '(angle-class-1 angle-class-2 angle-class-3)) '(1 2 3)) "angle equality classes not demonstrated")
      (check (not (shown t 'Cbisection)) "old bisector crosses the copied angle")
      (check (not (shown t 'Cbisector-mark)) "old arc persisted")))
  (cons "angle labels remain inside their sectors with estimated font boxes"
    (lambda ()
      (define t (build "copy-angle"))
      (define plan (prepare-geometry-annotations t))
      (for ([id '(source-mark target-mark)])
        (define spec (angle-marker-angle (hash-ref (v-of t) id)))
        (define vertex (angle-spec-b spec))
        (define u (point- (angle-spec-a spec) vertex))
        (define v (point- (angle-spec-c spec) vertex))
        (define d (point- (hash-ref (annotation-plan-labels plan) id) vertex))
        (define sign (if (positive? (cross u v)) 1 -1))
        (check (and (> (* sign (cross u d)) 0) (> (* sign (cross d v)) 0))
               "alpha is outside the angle" id))))
  (cons "the two object-scale preferences are preserved"
    (lambda ()
      (define style (resolve-geometry-style default-dark-geometry-theme 'Right-Angle-Marker 'normal))
      (near (hash-ref style 'size) 0.18)
      (near (geometry-timing-read-delay default-geometry-timing) 1.0)))
  ))

(define example-groups
 (for*/list ([name (in-list review-example-names)] [mode '(light dark)])
  (cons (format "all authored review steps and final annotations: ~a / ~a" name mode)
    (lambda ()
      (define t (build name mode))
      (define rows (make-geometry-review-plan t))
      (check (pair? rows) "empty review")
      (for ([row rows])
        (define s (geometry-review-step-span row))
        (check (or (not (geometry-step-span-narration s)) (string? (geometry-step-span-narration s))) "caption template escaped")
        (check (= 3 (length (geometry-review-step-samples row))) "triplet count")
        (check (equal? (geometry-review-step-caption row)
                      (geometry-frame-narration (geometry-review-sample-frame (car (geometry-review-step-samples row)))))
               "read caption differs from step")
        (check (<= (geometry-step-span-start s) (geometry-step-span-action-start s)
                   (geometry-step-span-action-end s) (geometry-step-span-end s)) "invalid ordering"))
      (for ([text (captions t)])
        (check (not (regexp-match? #rx"[Ee]mphasi|[Dd]eemphasi|[Hh]ighlight" text)) "narration announces styling" text))
      ;; Identical reviewed snapshots must be available in either request order.
      (define times (list 0 (/ (geometry-timeline-duration t) 2) (geometry-timeline-duration t)))
      (define samples (map (lambda (time) (sample-geometry-timeline t time)) times))
      (check (equal? (reverse samples) (map (lambda (time) (sample-geometry-timeline t time)) (reverse times))) "non-deterministic sampling")
      (for ([rule (geometry-program-layout (p-of t))] #:when (eq? (car rule) 'fit-circle))
        (for ([id (cdr rule)])
          (define circle (hash-ref (v-of t) id))
          (define radius (circle-radius circle))
          (define view (geometry-realization-view (geometry-timeline-realization t)))
          (for ([offset (list (point radius 0) (point (- radius) 0) (point 0 radius) (point 0 (- radius)))])
            (check (point-in-view? (point+ (circle-center circle) offset) view 0.45) "main circle leaves safe view" id))))))))

(define audit-check-groups (append basic-groups example-groups))
(define (run-audit-checks)
  (define count (box 0))
  (for ([group audit-check-groups])
    (printf "~a ... " (car group)) (flush-output)
    (parameterize ([total count] [current-name (car group)]) ((cdr group)))
    (displayln "ok"))
  (printf "~a audit groups, ~a checks passed.\n" (length audit-check-groups) (unbox count)))
