#lang racket/base

;; Base-only regression checks for the construction-like circle reveal.
(require racket/list (only-in racket/math pi)
         "../core.rkt" "../private/reveal.rkt" "../private/compiler.rkt")
(provide compass-check-groups run-compass-checks)

(define counter (make-parameter #f))
(define group-name (make-parameter "compass"))
(define (check condition message . values)
  (when (counter) (set-box! (counter) (add1 (unbox (counter)))))
  (unless condition
    (error 'compass-checks "~a: ~a ~s" (group-name) message values)))
(define (near-number a b [scale 1])
  (check (<= (abs (- a b)) (* 1e-8 (max 1 scale))) "numeric mismatch" a b))
(define (near-point a b)
  (near-number (distance a b) 0 (max 1 (norm a) (norm b))))
(define (compile clauses [helpers (hash)])
  (make-construction-program 'compass-check clauses helpers "compass-checks.rkt"))
(define (fails thunk)
  (check (with-handlers ([exn:fail:geometry? (lambda (_) #t)]) (thunk) #f)
         "expected geometry diagnostic"))

(define compass-check-groups
  (list
   (cons "carrier pickup, parallel lift, pulses and transport preserve the source measure"
     (lambda ()
       (define c (circle-with-radius (point 0 2) 2))
       (define source (compass-source (point 0 0) (point 2 0)))
       (define pickup (compass-circle-reveal c source (/ compass-draw-end 2)))
       (check (null? (compass-reveal-state-circle-strokes pickup)) "circle starts too early")
       (define pickup-line (car (compass-reveal-state-guide-strokes pickup)))
       (near-point (car pickup-line) (point 0 0))
       (near-point (cadr pickup-line) (point 1 0))
       (define lifted (compass-circle-reveal c source compass-offset-end))
       (define lifted-line (car (compass-reveal-state-guide-strokes lifted)))
       (near-number (distance (car lifted-line) (cadr lifted-line)) 2)
       (near-number (point-y (car lifted-line)) (point-y (cadr lifted-line)))
       (check (> (point-y (car lifted-line)) 0) "parallel lift chose caption side")
       (define source-pulse
         (compass-circle-reveal c source compass-review-source-attention-progress))
       (near-number (compass-reveal-state-guide-attention source-pulse) 1)
       (define transport
         (compass-circle-reveal c source compass-review-transport-progress))
       (define transport-line (car (compass-reveal-state-guide-strokes transport)))
       (near-number (distance (car transport-line) (cadr transport-line)) 2)
       (define ready (compass-circle-reveal c source compass-transport-end))
       (define ready-line (car (compass-reveal-state-guide-strokes ready)))
       (near-point (car ready-line) (circle-center c))
       (near-number (distance (car ready-line) (cadr ready-line)) 2)
       (define target-pulse
         (compass-circle-reveal c source compass-review-target-attention-progress))
       (near-number (compass-reveal-state-guide-attention target-pulse) 1)))
   (cons "sweep tip is exactly the circle trace endpoint"
     (lambda ()
       (define c (circle-with-radius (point 0 2) 2))
       (define source (compass-source (point 0 0) (point 2 0)))
       (for ([p (in-list (list (+ compass-target-attention-end 0.01)
                               compass-review-sweep-progress 0.90 0.99 1.0))])
         (define state (compass-circle-reveal c source p))
         (define guide (car (compass-reveal-state-guide-strokes state)))
         (define arc (car (compass-reveal-state-circle-strokes state)))
         (near-point (car guide) (circle-center c))
         (near-point (cadr guide) (last (reveal-arc-points arc)))
         (near-number (distance (car guide) (cadr guide)) (circle-radius c)))
       (define half (compass-circle-reveal c source compass-review-sweep-progress))
       (near-number (reveal-arc-sweep (car (compass-reveal-state-circle-strokes half))) pi)
       (define done (compass-circle-reveal c source 1))
       (near-number (reveal-arc-sweep (car (compass-reveal-state-circle-strokes done))) (* 2 pi))
       (check (reveal-arc-closed? (car (compass-reveal-state-circle-strokes done))) "final arc not closed")
       (near-number (compass-reveal-state-guide-opacity done) 0)
       (near-number (compass-reveal-state-guide-attention done) 0)))
   (cons "automatic provenance follows segment lengths, distances and aliases"
     (lambda ()
       (define p
         (compile '((given [A (point -2 0)] [B (point 0 0)] [O (point 3 0)])
                    (step [AB (segment A B)])
                    (step [r (length AB)])
                    (step [c1 (circle O #:radius r)])
                    (step [c2 (circle O #:radius (distance A B))])
                    (step [c3 (circle O #:radius 2)])
                    (step [c4 (circle O #:radius (* 2 (length AB)))]))))
       (define env (geometry-realization-values (realize-construction p)))
       (for ([id '(c1 c2)])
         (define-values (mode source) (resolve-circle-reveal p id env))
         (check (eq? mode 'compass) "traceable radius did not choose compass" id)
         (check (compass-source? source) "missing source" id)
         (near-number (distance (compass-source-a source) (compass-source-b source)) 2))
       (for ([id '(c3 c4)])
         (define-values (fallback-mode fallback-source) (resolve-circle-reveal p id env))
         (check (eq? fallback-mode 'bidirectional) "numeric/arithmetic radius should use ordinary reveal" id)
         (check (not fallback-source) "numeric/arithmetic radius invented a source" id))))
   (cons "ordinary through-point circles remain bidirectional unless explicitly forced"
     (lambda ()
       (define automatic
         (compile '((given [O (point 0 0)] [P (point 2 0)])
                    (step [c (circle O P)]))))
       (define auto-env (geometry-realization-values (realize-construction automatic)))
       (define-values (auto-mode auto-source) (resolve-circle-reveal automatic 'c auto-env))
       (check (eq? auto-mode 'bidirectional) "through-point default changed")
       (check (not auto-source) "through-point default gained a source")
       (define forced
         (compile '((given [O (point 0 0)] [P (point 2 0)])
                    (reveal [c compass])
                    (step [c (circle O P)]))))
       (define forced-env (geometry-realization-values (realize-construction forced)))
       (define-values (forced-mode forced-source) (resolve-circle-reveal forced 'c forced-env))
       (check (eq? forced-mode 'compass) "forced mode ignored")
       (near-point (compass-source-a forced-source) (point 0 0))
       (near-point (compass-source-b forced-source) (point 2 0))))
   (cons "forcing compass without geometric provenance is diagnosed"
     (lambda ()
       (define p
         (compile '((given [O (point 0 0)])
                    (reveal [c compass])
                    (step [c (circle O #:radius 2)]))))
       (define env (geometry-realization-values (realize-construction p)))
       (fails (lambda ()
                (call-with-values (lambda () (resolve-circle-reveal p 'c env))
                  (lambda _ (void)))))))
   (cons "provenance survives helper argument and result aliases"
     (lambda ()
       (define helper
         (make-construction-helper
          'make-radius-circle
          '((given [source : Segment] [O : Point])
            (results Circle)
            (step [r (length source)])
            (step [c (circle O #:radius r)])
            (result c))
          (hash)
          "compass helper"))
       (define p
         (compile '((given [A (point -2 0)] [B (point 0 0)] [O (point 3 0)])
                    (step [AB (segment A B)])
                    (step (expand [c (make-radius-circle AB O)])))
                  (hash 'make-radius-circle helper)))
       (define env (geometry-realization-values (realize-construction p)))
       (define-values (mode source) (resolve-circle-reveal p 'c env))
       (check (eq? mode 'compass) "helper source was lost")
       (near-number (distance (compass-source-a source) (compass-source-b source)) 2)))
   (cons "automatic compass timing defaults to ten seconds but explicit overrides win"
     (lambda ()
       (define p
         (compile '((given [A (point -2 0)] [B (point 0 0)] [O (point 3 0)])
                    (step [AB (segment A B)])
                    (step [c (circle O #:radius (length AB))]))))
       (define (circle-event timeline)
         (findf
          (lambda (event)
            (for/or ([a (in-list (geometry-event-actions event))])
              (and (eq? (geometry-action-kind a) 'reveal)
                   (memq 'c (geometry-action-targets a)))))
          (geometry-timeline-events timeline)))
       (define automatic (circle-event (construction->timeline p)))
       (check automatic "missing automatic compass event")
       (near-number (- (geometry-event-end automatic) (geometry-event-start automatic)) 10)
       (define overridden (circle-event (construction->timeline p #:action-duration 2)))
       (check overridden "missing overridden compass event")
       (near-number (- (geometry-event-end overridden) (geometry-event-start overridden)) 2)))
   (cons "guide and attention themes are independent of mathematical circle style"
     (lambda ()
       (for ([theme (list default-light-geometry-theme default-dark-geometry-theme)])
         (define guide (resolve-geometry-style theme 'compass-guide 'normal))
         (define attention (resolve-geometry-style theme 'compass-attention 'normal))
         (check (eq? (hash-ref guide 'dash) 'solid) "guide dash")
         (near-number (hash-ref guide 'stroke-width) 2.5)
         (near-number (hash-ref guide 'opacity) 1)
         (check (eq? (hash-ref guide 'stroke-color) 'highlight) "guide color")
         (check (eq? (hash-ref attention 'dash) 'solid) "attention dash")
         (near-number (hash-ref attention 'stroke-width) 9)
         (near-number (hash-ref attention 'opacity) 0.45)
         (check (eq? (hash-ref attention 'stroke-color) 'highlight) "attention color"))))))

(define (run-compass-checks)
  (define counts (box 0))
  (for ([group (in-list compass-check-groups)])
    (printf "~a ... " (car group)) (flush-output)
    (parameterize ([counter counts] [group-name (car group)]) ((cdr group)))
    (displayln "ok"))
  (printf "~a compass groups, ~a checks passed.\n"
          (length compass-check-groups) (unbox counts))
  (hash 'groups (length compass-check-groups) 'checks (unbox counts)))

(module+ main (run-compass-checks))
