#lang racket/base
(require "../core.rkt" "../examples/helpers.rkt")
(provide triangle bisector-demo perpendicular collapsed expanded state-demo pair-helper pair-demo)

(construction triangle
  (given [A (point -2 0)] [B (point 2 0)])
  (timing [opening-pause 0.6] [read-delay 1.0] [action-duration 0.9] [step-pause 0.5])
  (require (distinct? A B))
  (layout (focus A B C))
  (step "AB" [AB (segment A B)])
  (step "First circle" [cA (circle A B)])
  (step "Second circle" [cB (circle B A)])
  (step "C" [C (intersection cA cB #:side-of AB 'left)])
  (step "Sides" (together [AC (segment A C)] [BC (segment B C)]))
  (step "Result" (deemphasize cA cB) (highlight AB AC BC)))
(construction bisector-demo
  (given [A (point)] [B (point)])
  (timing [opening-pause 0.6] [read-delay 1.0] [action-duration 0.9] [step-pause 0.5])
  (require (distinct? A B))
  (layout (focus A B M) (prefer (distance A B) 3.5))
  (step "AB" [AB (segment A B)])
  (step "Bisector" (expand [m (perpendicular-bisector A B)]))
  (step "Midpoint" [M (intersection m AB)]))
(construction perpendicular
  (given [l (line (point -3 0) (point 3 0))] [P (point 0 0)])
  (timing [opening-pause 0.6] [read-delay 1.0] [action-duration 0.9] [step-pause 0.5])
  (require (on P l))
  (layout (focus A B C D P) (prefer (distance A P) 1.5))
  (step "A" [A (choose (point-on l #:except P))])
  (step "Circle P" [cP (circle P A)])
  (step "B" [B (intersection cP l #:other-than A)])
  (step "Circles" [cA (circle A B)] [cB (circle B A)])
  (step "Intersections" [(C D) (intersections cA cB)])
  (step "Perpendicular" [m (line C D)])
  (step "Conclusion" (deemphasize cP cA cB) (hide-label A B C D) (highlight m P)))
(construction collapsed
  (given [A (point -2 0)] [B (point 2 0)] [C (point 1 3)])
  (timing [opening-pause 0.6] [read-delay 1.0] [action-duration 0.9] [step-pause 0.5])
  (step "Two helpers" [m1 (perpendicular-bisector A B)] [m2 (perpendicular-bisector B C)])
  (step "Circumcenter" [O (intersection m1 m2)]))
(construction expanded
  (given [A (point -2 0)] [B (point 2 0)])
  (timing [opening-pause 0.6] [read-delay 1.0] [action-duration 0.9] [step-pause 0.5])
  (step "Helper" (expand [m (perpendicular-bisector A B)])))
(construction state-demo
  (given [A (point 0 0)] [B (point 3 0)])
  (timing [opening-pause 0.25] [read-delay 0.5] [action-duration 0.8] [step-pause 0.4])
  (initially (hide A) (hide-label A))
  (step "Show" (show A))
  (step "Label" (show-label A))
  (step "New hidden label" [C (midpoint A B)] (hide-label C))
  (step "Dim" (deemphasize C))
  (step "Pulse" (highlight C))
  (step #:read-delay 0.3 #:duration 0.6 #:pause 0.2 "Hide" (hide C))
  (step "Show again" (show C))
  (step "Normal" (normalize C))
  (step "Label again" (show-label C)))
(define-construction pair-helper
  (given [A : Point] [B : Point])
  (results Point Segment)
  (step [M (midpoint A B)] [s (segment A B)])
  (result M s))
(construction pair-demo
  (given [A (point -2 0)] [B (point 2 0)])
  (timing [opening-pause 0.6] [read-delay 1.0] [action-duration 0.9] [step-pause 0.5])
  (step [(M AB) (pair-helper A B)]))
