#lang racket/base

;; Base-only narration and output-planning checks. Native subtitle values and
;; the actual Animate serializer are tested separately in subtitle-render-test.
(require racket/list racket/path racket/runtime-path
         "../core.rkt" "../private/subtitle-output.rkt"
         "../examples/private/review-example-names.rkt")
(provide subtitle-check-groups run-subtitle-checks)
(define-runtime-path examples "../examples")
(define checks (make-parameter #f))
(define (ensure value message . args)
  (when (checks) (set-box! (checks) (add1 (unbox (checks)))))
  (unless value (apply error 'subtitle-checks message args)))
(define (equal! a b)
  (ensure (equal? a b) "expected ~e, got ~e" b a))
(define (fails! thunk)
  (ensure (with-handlers ([exn:fail? (lambda (_) #t)]) (thunk) #f) "expected an error"))
(construction bare (given [A (point 0 0)]))
(define (with-cues cues [duration 15])
  (struct-copy geometry-timeline (construction->timeline bare)
               [cues cues] [duration duration]))
(define (simple cues)
  (map (lambda (c) (list (geometry-cue-start c) (geometry-cue-end c) (geometry-cue-text c))) cues))
(construction slow-compass
  (given [A (point -2 1)] [B (point 0 1)] [O (point 3 1)])
  (step "Use AB as the radius." [AB (segment A B)])
  (step "Draw the circle centred at O." [c (circle O #:radius (length AB))])
  (step "The circle is complete."))
(define (canon p) (simplify-path (path->complete-path p)))
(define basic
  (list
   (cons "empty timelines and zero-duration cues do not invent subtitles"
         (lambda ()
           (equal! (geometry-caption-cues (construction->timeline bare)) '())
           (equal! (geometry-caption-cues (with-cues (list (geometry-cue 2 2 "Instant")))) '())))
   (cons "nested helper narration follows the visual precedence and resumes its parent"
         (lambda ()
           (define t (with-cues (list (geometry-cue 4 6 "Inner")
                                     (geometry-cue 2 8 "Child")
                                     (geometry-cue 0 10 "Parent")
                                     (geometry-cue 10 12 "Parent"))))
           (equal! (simple (geometry-caption-cues t))
                   '((0 2 "Parent") (2 4 "Child") (4 6 "Inner") (6 8 "Child") (8 12 "Parent")))))
   (cons "identical text merges only when the intervals touch"
         (lambda ()
           (define t (with-cues (list (geometry-cue 0 1 "Same") (geometry-cue 1 2 "Same")
                                     (geometry-cue 4 5 "Same"))))
           (equal! (simple (geometry-caption-cues t)) '((0 2 "Same") (4 5 "Same")))))
   (cons "ties use the same stable source-order precedence as on-screen captions"
         (lambda ()
           (define t (with-cues (list (geometry-cue 0 4 "First") (geometry-cue 2 6 "Second"))))
           (equal! (simple (geometry-caption-cues t)) '((0 4 "First") (4 6 "Second")))))
   (cons "Unicode, authored line breaks and exact fractional seconds are retained"
         (lambda ()
           (define text "Lad A′ være et punkt.\nα < β; Æ Ø Å; P₁")
           (define t (with-cues (list (geometry-cue 1/3 7/3 text))))
           (equal! (simple (geometry-caption-cues t)) (list (list 1/3 7/3 text)))))
   (cons "explicit silent cues preserve gaps without altering their parent timing"
         (lambda ()
           (define t (with-cues (list (geometry-cue 0 5 "Parent") (geometry-cue 2 3 #f))))
           (equal! (simple (geometry-caption-cues t)) '((0 2 "Parent") (3 5 "Parent")))))
   (cons "numerically equal exact/inexact boundaries never create zero-length subtitles"
         (lambda ()
           (define t (with-cues (list (geometry-cue 0 1 "First") (geometry-cue 1.0 2 "Second"))))
           (define cues (geometry-caption-cues t))
           (ensure (= (length cues) 2) "numeric boundary was duplicated")
           (ensure (andmap (lambda (c) (< (geometry-cue-start c) (geometry-cue-end c))) cues)
                   "zero-length cue from exact/inexact duplicate")
           (ensure (= (geometry-cue-end (car cues)) (geometry-cue-start (cadr cues))) "boundary gap")))
   (cons "ten-second compass actions and their reading/ending pauses keep correct cue bounds"
         (lambda ()
           (define t (construction->timeline slow-compass))
           (define event
             (findf (lambda (e) (for/or ([a (in-list (geometry-event-actions e))])
                                  (memq 'c (geometry-action-targets a))))
                    (geometry-timeline-events t)))
           (ensure (< (abs (- (- (geometry-event-end event) (geometry-event-start event)) 10)) 1e-8)
                   "the accepted ten-second compass default changed")
           (define cs (geometry-caption-cues t))
           (define caption (findf (lambda (c) (equal? (geometry-cue-text c) "Draw the circle centred at O.")) cs))
           (ensure (<= (geometry-cue-start caption) (geometry-event-start event)
                       (geometry-event-end event) (geometry-cue-end caption)) "cue does not cover the full action")
           (equal! cs (geometry-caption-cues t))))
   (cons "invalid public inputs fail before exporting"
         (lambda ()
           (fails! (lambda () (geometry-caption-cues #f)))
           (fails! (lambda () (geometry-caption-cues (with-cues (list (geometry-cue -1 1 "Bad"))))))
           (fails! (lambda () (geometry-caption-cues (with-cues (list (geometry-cue 1 20 "Bad"))))))))
   (cons "MP4 output automatically plans the legacy SRT and the adjacent sidecar"
         (lambda ()
           (equal! (geometry-subtitle-output-plan #:directory "frames" #:mp4 "videos/lesson.mp4")
                   (list (cons (canon "frames/narration.srt") 'srt)
                         (cons (canon "videos/lesson.srt") 'srt)))))
   (cons "explicit SRT replaces the MP4 sidecar; WebVTT is additive"
         (lambda ()
           (equal! (geometry-subtitle-output-plan #:directory "frames" #:mp4 "videos/lesson.mp4"
                                                  #:srt "captions/lesson.en.srt" #:vtt "captions/lesson.en.vtt")
                   (list (cons (canon "frames/narration.srt") 'srt)
                         (cons (canon "captions/lesson.en.srt") 'srt)
                         (cons (canon "captions/lesson.en.vtt") 'webvtt)))))
   (cons "the MP4 subtitle track uses the explicit SRT or the automatic adjacent sidecar"
         (lambda ()
           (equal! (geometry-mp4-subtitle-path "videos/lesson.mp4")
                   (canon "videos/lesson.srt"))
           (equal! (geometry-mp4-subtitle-path "videos/lesson.mp4" "captions/lesson.en.srt")
                   (canon "captions/lesson.en.srt"))
           (equal! (geometry-mp4-subtitle-path #f) #f)
           (fails! (lambda () (geometry-mp4-subtitle-path "lesson.mp4" 42)))))
   (cons "same canonical SRT destination is written once, and different formats cannot collide"
         (lambda ()
           (equal! (length (geometry-subtitle-output-plan #:directory "frames" #:srt "frames/./narration.srt")) 1)
           (fails! (lambda () (geometry-subtitle-output-plan #:srt "same.txt" #:vtt "./same.txt")))
           (fails! (lambda () (geometry-subtitle-output-plan #:mp4 "video.mp4" #:srt "./video.mp4")))))
   (cons "paths with whitespace/Unicode remain paths; subtitle-only planning creates no legacy output"
         (lambda ()
           (equal! (geometry-subtitle-output-plan #:srt "Subtitles/John's α lesson.srt")
                   (list (cons (canon "Subtitles/John's α lesson.srt") 'srt)))
           (equal! (geometry-subtitle-output-plan) '())
           (fails! (lambda () (geometry-subtitle-output-plan #:srt 42)))))))

(define (check-example name theme)
  (define factory (dynamic-require (build-path examples (string-append name ".rkt")) 'make-demo-timeline))
  (define t (factory #:theme-mode theme))
  (define original t)
  (define cues (geometry-caption-cues t))
  (for ([c (in-list cues)])
    (ensure (< (geometry-cue-start c) (geometry-cue-end c)) "nonpositive subtitle interval")
    (ensure (<= 0 (geometry-cue-start c) (geometry-cue-end c) (geometry-timeline-duration t)) "cue out of bounds")
    (equal! (geometry-cue-text c)
            (geometry-timeline-narration-at t (/ (+ (geometry-cue-start c) (geometry-cue-end c)) 2))))
  (for ([a (in-list cues)] [b (in-list (if (pair? cues) (cdr cues) '()))])
    (ensure (<= (geometry-cue-end a) (geometry-cue-start b)) "export cues overlap")
    (ensure (not (and (= (geometry-cue-end a) (geometry-cue-start b))
                      (equal? (geometry-cue-text a) (geometry-cue-text b)))) "adjacent identical captions were not merged"))
  ;; Exhaust all original cue boundaries, including every nested helper interval.
  (define boundaries (sort (remove-duplicates
                            (append (list 0 (geometry-timeline-duration t))
                                    (append-map (lambda (c) (list (geometry-cue-start c) (geometry-cue-end c)))
                                                (geometry-timeline-cues t)))) <))
  (for ([a (in-list boundaries)] [b (in-list (cdr boundaries))])
    (define x (/ (+ a b) 2))
    (define matches (filter (lambda (c) (and (<= (geometry-cue-start c) x) (< x (geometry-cue-end c)))) cues))
    (ensure (<= (length matches) 1) "multiple effective captions at ~a" x)
    (equal! (and (pair? matches) (geometry-cue-text (car matches))) (geometry-timeline-narration-at t x)))
  (equal! cues (geometry-caption-cues t))
  (equal! original t))
(define subtitle-check-groups
  (append basic
          (for*/list ([name (in-list review-example-names)] [theme '(light dark)])
            (cons (format "effective subtitle intervals: ~a / ~a" name theme)
                  (lambda () (check-example name theme))))))
(define (run-subtitle-checks)
  (define n (box 0))
  (parameterize ([checks n])
    (for ([g (in-list subtitle-check-groups)])
      (printf "~a ... " (car g)) (flush-output)
      ((cdr g)) (displayln "ok")))
  (printf "~a subtitle groups, ~a checks passed.\n" (length subtitle-check-groups) (unbox n)))
(module+ main (run-subtitle-checks))
