#lang racket/base
(require rackunit racket/list "../core.rkt" "../private/compiler.rkt" "fixtures.rkt")
(define (event-for timeline kind id)
  (or (findf (lambda (event)
               (ormap (lambda (a) (and (eq? (geometry-action-kind a) kind)
                                       (memq id (geometry-action-targets a))))
                       (geometry-event-actions event))) (geometry-timeline-events timeline))
      (error 'test "event not found: ~a ~a" kind id)))
(define (at timeline id time) (hash-ref (geometry-frame-appearances (sample-geometry-timeline timeline time)) id))
(define (middle event) (/ (+ (geometry-event-start event) (geometry-event-end event)) 2))
(module+ test
  (define timeline (construction->timeline state-demo))
  (test-case "initially controls objects and labels independently"
    (check-equal? (geometry-appearance-opacity (at timeline 'A 0)) 0)
    (check-equal? (geometry-appearance-label-opacity (at timeline 'A 0)) 0)
    (check-equal? (geometry-appearance-opacity (at timeline 'B 0)) 1))
  (test-case "showing a point respects an explicitly hidden label"
    (define end (geometry-event-end (event-for timeline 'show 'A)))
    (check-equal? (geometry-appearance-opacity (at timeline 'A end)) 1)
    (check-equal? (geometry-appearance-label-opacity (at timeline 'A end)) 0))
  (test-case "show-label reveals a label independently"
    (define e (event-for timeline 'show-label 'A))
    (check-true (< 0 (geometry-appearance-label-opacity (at timeline 'A (middle e))) 1))
    (check-equal? (geometry-appearance-opacity (at timeline 'A (middle e))) 1))
  (test-case "same-step hide-label never flashes a newborn point label"
    (define e (event-for timeline 'reveal 'C))
    (for ([fraction (in-list '(0 1/10 1/2 9/10 1))])
      (define t (+ (geometry-event-start e) (* fraction (- (geometry-event-end e) (geometry-event-start e)))))
      (check-equal? (geometry-appearance-label-opacity (at timeline 'C t)) 0)))
  (test-case "highlight is transient and restores secondary presentation"
    (define e (event-for timeline 'highlight 'C))
    (define during (at timeline 'C (middle e)))
    (define after (at timeline 'C (geometry-event-end e)))
    (check-equal? (geometry-appearance-secondary during) 1)
    (check-= (geometry-appearance-highlight during) 1 1e-8)
    (check-equal? (geometry-appearance-secondary after) 1)
    (check-equal? (geometry-appearance-highlight after) 0))
  (test-case "hiding does not destroy geometry or reset its label preference"
    (define e (event-for timeline 'hide 'C))
    (check-equal? (geometry-appearance-opacity (at timeline 'C (geometry-event-end e))) 0)
    (check-= (distance (construction-ref (geometry-timeline-realization timeline) 'C) (point 1.5 0)) 0 1e-8)
    (define show (event-for timeline 'show 'C))
    (check-equal? (geometry-appearance-label-opacity (at timeline 'C (geometry-event-end show))) 0)
    (check-equal? (geometry-appearance-secondary (at timeline 'C (geometry-event-end show))) 1))
  (test-case "normalize changes prominence without changing geometry"
    (define e (event-for timeline 'normalize 'C))
    (check-equal? (geometry-appearance-secondary (at timeline 'C (geometry-event-end e))) 0))
  (test-case "sampling is independent of request order"
    (define times (list 0 2.3 1.7 (geometry-timeline-duration timeline) 0.6))
    (define first (map (lambda (t) (sample-geometry-timeline timeline t)) times))
    (for ([t (in-list (reverse times))]) (sample-geometry-timeline timeline t))
    (check-equal? first (map (lambda (t) (sample-geometry-timeline timeline t)) times)))
  (test-case "construction timing inserts a read delay before first action"
    (define p (make-construction-program 'timed '((given [A (point 0 0)] [B (point 2 0)])
                                                 (timing [opening-pause 0.2] [read-delay 0.5] [action-duration 1.25] [step-pause 0.4])
                                                 (step "AB" [AB (segment A B)])) (hash) "test"))
    (define t (construction->timeline p))
    (define e (event-for t 'reveal 'AB))
    (check-= (geometry-event-start e) 0.7 1e-8)
    (check-= (geometry-event-end e) 1.95 1e-8)
    (check-= (geometry-timeline-duration t) 2.35 1e-8)
    (check-equal? (geometry-frame-narration (sample-geometry-timeline t 0.3)) "AB"))
  (test-case "silent steps do not receive the default reading delay"
    (define p (make-construction-program 'timed '((given [A (point 0 0)] [B (point 2 0)])
                                                 (timing [opening-pause 0] [read-delay 0.8] [action-duration 0.5] [step-pause 0])
                                                 (step [AB (segment A B)])) (hash) "test"))
    (define t (construction->timeline p))
    (define e (event-for t 'reveal 'AB))
    (check-= (geometry-event-start e) 0 1e-8)
    (check-= (geometry-event-end e) 0.5 1e-8))
  (test-case "per-step timing overrides the construction defaults"
    (define p (make-construction-program 'timed '((given [A (point 0 0)])
                                                 (initially (hide A))
                                                 (timing [opening-pause 0.2] [read-delay 0.5] [action-duration 1.25] [step-pause 0.4])
                                                 (step #:read-delay 0.1 #:duration 0.6 #:pause 0.2 "Show" (show A))) (hash) "test"))
    (define t (construction->timeline p))
    (define e (event-for t 'show 'A))
    (check-= (geometry-event-start e) 0.3 1e-8)
    (check-= (geometry-event-end e) 0.9 1e-8)
    (check-= (geometry-timeline-duration t) 1.1 1e-8))
  (test-case "redundant show and hide operations consume no transition time"
    (define p (make-construction-program
               'noops '((given [A (point 0 0)]) (step (show A) (show A) (hide A) (hide A))) (hash) "test"))
    (define t (construction->timeline p #:opening-hold 0 #:hold 0 #:read-delay 0 #:action-duration 1))
    (check-equal? (length (geometry-timeline-events t)) 1)
    (check-equal? (geometry-timeline-duration t) 1))
  (test-case "expanded helper narration is available during its child steps"
    (define t (construction->timeline expanded))
    (check-true (> (length (geometry-timeline-cues t)) 1))
    (check-not-false (geometry-timeline-narration-at t 1)))
  (test-case "completed timelines retain the final caption and scene"
    (check-equal? (geometry-frame-narration (sample-geometry-timeline timeline (geometry-timeline-duration timeline)))
                  "Label again")
    (check-equal? (geometry-frame-appearances (sample-geometry-timeline timeline 100000))
                  (geometry-frame-appearances (sample-geometry-timeline timeline (geometry-timeline-duration timeline))))))
