#lang racket/base

;; Executed without RackUnit, GUI, or renderer stubs. The RackUnit wrapper uses
;; the same groups. Geometric oracles do not call the transform under test.
(require racket/list racket/runtime-path (only-in racket/math pi)
         "../core.rkt" "../private/compiler.rkt" "../private/evaluate.rkt"
         "../private/drawing.rkt" "../private/marker-shapes.rkt" "../review-plan.rkt")
(provide transform-label-check-groups run-transform-label-checks)
(define count (make-parameter #f))
(define context (make-parameter "transform-label-checks"))
(define (check x message . args)
  (when (count) (set-box! (count) (add1 (unbox (count)))))
  (unless x (error 'transform-label-checks "~a: ~a ~e" (context) message args)))
(define (near a b [scale 1])
  (check (<= (abs (- a b)) (* 1e-8 (max 1 (abs scale)))) "numeric mismatch" a b))
(define (same a b) (near (distance a b) 0 (max 1 (norm a) (norm b))))
(define (fails thunk [rx #rx"."])
  (define e (with-handlers ([exn:fail:geometry? values]) (thunk) #f))
  (check (and e (regexp-match? rx (exn-message e))) "expected geometry error" e))
(define (compile clauses [helpers (hash)])
  (make-construction-program 'check clauses helpers "transform-label-checks"))
(define (value-of program id)
  (construction-ref (realize-construction program) id))
(define P (point 1.25 -2.5))
(define A (point -2 1)) (define B (point 3 2)) (define C (point 1 4))
(define s (segment A B))
(define c (circle A C))
(define a (angle-spec B A C))
(define axis (line (point 1 -1) (point 4 2)))
(define T (translation (geometry-vector 4 -1)))
(define R (rotation (point 2 1) (degrees 37)))
(define F (reflection axis))
(define D (dilation (point -1 3) -2))
(define transforms (list (identity-transform) T R F D (compose-transform T R F D)))
(define objects (list A s (line A C) (ray B C) c a))

(define-construction image-with-name
  (given [source : Segment] [mapping : Transform] [name : Text])
  (results Segment Label)
  (step "Construct the image and label its length."
    [image (transform mapping source)] [caption (length-label image name)])
  (layout (label-position caption 0.4))
  (result image caption))
(construction typed-helper-demo
  (given [A (point -2 0)] [B (point 1 0)]
         [source (segment A B)] [T (translation (vector 0 2))])
  (step "Use a transformation as a helper argument."
    (expand [(image caption) (image-with-name source T "a′")] #:auxiliaries 'hide)))

(define-construction outside-side-name
  (given [A : Point] [B : Point] [C : Point])
  (results Label)
  (step [BC (segment B C)] [a (length-label BC "a")])
  (layout (label-outside-of a A))
  (result a))
(construction outside-helper-demo
  (given [P (point 0 2)] [Q (point -2 0)] [R (point 2 0)])
  (step "Reuse an outside side label."
    (expand [side-name (outside-side-name P Q R)] #:auxiliaries 'hide)))

(define transformation-groups
  (append
   (list
    (cons "vectors and degrees are typed values"
      (lambda ()
        (define v (vector-between A B))
        (check (equal? v (geometry-vector 5 1)) "vector-between order")
        (check (eq? (geometry-kind v) 'Vector) "vector kind")
        (near (degrees 180) pi)
        (check (eq? (geometry-kind T) 'Transform) "transform kind")
        (check (= (transformation-orientation F) -1) "reflection orientation")
        (check (= (transformation-orientation D) 1) "negative 2D scale orientation")
        (near (transformation-scale D) 2)))
    (cons "composition order is rightmost first"
      (lambda ()
        (define t (translation (geometry-vector 3 0)))
        (define r (rotation (point 0 0) (degrees 90)))
        (same (transform (compose-transform t r) (point 1 0)) (point 3 1))
        (same (transform (compose-transform r t) (point 1 0)) (point 0 4))
        (same (transform (compose-transform) A) A)))
    (cons "reflection matches an independent perpendicular projection"
      (lambda ()
        (for* ([p (list A B C P)] [l (list axis (line (point 0 0) (point 0 1))
                                               (line (point 0 2) (point 2 2)))])
          (define u (point- (line-b l) (line-a l)))
          (define h (point+ (line-a l) (point* u (/ (dot (point- p (line-a l)) u) (dot u u)))))
          (same (reflect p l) (point- (point* h 2) p))
          (same (reflect (reflect p l) l) p))))
    (cons "clockwise and counterclockwise rotations and negative dilations"
      (lambda ()
        (same (rotate (point 2 0) (point 0 0) (degrees 90)) (point 0 2))
        (same (rotate (point 2 0) (point 0 0) (degrees -90)) (point 0 -2))
        (same (dilate (point 2 3) (point 1 1) -3) (point -2 -5))
        (check (equal? (transform (identity-transform) s) s) "exact identity")
        (same (transform (rotation C 1.7) C) C)
        (same (transform (dilation C -3) C) C)))
    (cons "rotation versus independent coordinate formula"
      (lambda ()
        (for* ([theta '(0 0.23 -1.1 2.5)] [p (list A B C P)])
          (define u (point- p C))
          (same (rotate p C theta)
                (point+ C (point (- (* (cos theta) (point-x u)) (* (sin theta) (point-y u)))
                                 (+ (* (sin theta) (point-x u)) (* (cos theta) (point-y u))))))))))
   (for/list ([t transforms] [i (in-naturals)])
     (cons (format "similarity ~a: inversion, scale, incidence, angle and circle" i)
       (lambda ()
         (for ([p (list A B C P)]) (same (transform (inverse-transform t) (transform t p)) p))
         (for ([v objects]) (check (eq? (geometry-kind (transform t v)) (geometry-kind v)) "type preservation" v))
         (near (distance (transform t A) (transform t B)) (* (transformation-scale t) (distance A B)))
         (near (angle-measure (transform t a)) (angle-measure a))
         (near (angle-sweep (transform t a)) (* (transformation-orientation t) (angle-sweep a)))
         (check (on (transform t A) (transform t s)) "segment incidence")
         (check (on (transform t C) (transform t c)) "circle incidence")
         (near (circle-radius (transform t c)) (* (transformation-scale t) (circle-radius c)))
         (same (circle-through (transform t c)) (transform t (circle-through c)))
         (same (ray-a (transform t (ray A B))) (transform t A))
         (check (on (transform t (point+ A (point* (point- B A) 2))) (transform t (ray A B))) "ray direction")
         (for ([theta '(0 0.5 1.7 3 4.6 6)])
           (define p (point+ (circle-center c) (point (* (circle-radius c) (cos theta)) (* (circle-radius c) (sin theta)))))
           (near (distance (circle-center (transform t c)) (transform t p)) (circle-radius (transform t c)))))))
   (for*/list ([t transforms] [u transforms])
     (cons (format "composition/inverse pair ~a/~a" (index-of transforms t) (index-of transforms u))
       (lambda ()
         (for ([p (list A B C)])
           (same (transform (compose-transform t u) p) (transform t (transform u p)))
           (same (transform (inverse-transform (compose-transform t u)) (transform (compose-transform t u) p)) p)))))
   (list
    (cons "relations and markers are mapped without claiming false facts"
      (lambda ()
        (define origin (point 0 0))
        (define h (line (point -2 0) (point 2 0)))
        (define v (line (point 0 -2) (point 0 2)))
        (define rel (perpendicular-relation h v origin))
        (for ([t transforms])
          (check (relation-holds? (transform t rel)) "perpendicular preservation")
          (check (marker? (transform t (relation->marker rel))) "marker type")
          (check (relation-holds? (transform t (midpoint-of-relation origin (segment (point -2 0) (point 2 0))))) "midpoint preservation")
          (check (not (relation-holds? (transform t (parallel-relation h v)))) "false statement became true"))))
    (cons "geometry transformations do not mutate their sources"
      (lambda ()
        (define original (list A B c s))
        (for* ([t transforms] [v original]) (transform t v))
        (check (equal? original (list (point -2 1) (point 3 2) (circle (point -2 1) (point 1 4))
                                      (segment (point -2 1) (point 3 2)))) "source mutation")))
    (cons "invalid or singular transformation parameters fail"
      (lambda ()
        (for ([thunk (list (lambda () (dilation A 0)) (lambda () (rotation A +nan.0))
                           (lambda () (reflection s)) (lambda () (geometry-vector +inf.0 0))
                           (lambda () (transform 4 A)) (lambda () (compose-transform T 'bad))
                           (lambda () (transform T (point-label A "A"))))])
          (fails thunk)))))))

(define semantic-groups
 (list
  (cons "all four semantic label constructors"
   (lambda ()
    (define p (point-label A "A′")) (define q (segment-label s "5 cm"))
    (define r (length-label s "a")) (define u (angle-label a "α"))
    (for ([v (list p q r u)])
      (check (semantic-label? v) "not a label") (check (eq? (geometry-kind v) 'Label) "label kind")
      (check (immutable? (semantic-label-text v)) "text not frozen"))
    (check (semantic-label-arc? u) "missing arc")
    (check (not (semantic-label-arc? (angle-label a "α" #:arc? #f))) "unrequested arc")))
  (cons "measured values and units come from the target"
   (lambda ()
    (define seg (segment (point 0 0) (point 3 4)))
    (check (equal? (semantic-label-text (length-label seg #:precision 2 #:unit "cm")) "5.00 cm") "length formatting")
    (check (equal? (semantic-label-text (length-label seg #:precision 0)) "5") "zero-precision length has dangling decimal point")
    (check (equal? (semantic-label-text (length-label (dilate seg A -2) #:precision 1)) "10.0") "image length not recomputed")
    (define right-angle (angle-spec (point 1 0) (point 0 0) (point 0 1)))
    (check (equal? (semantic-label-text (angle-label right-angle #:precision 1)) "90.0°") "angle degrees")
    (check (equal? (semantic-label-text (angle-label right-angle #:precision 0)) "90°") "zero-precision angle has dangling decimal point")
    (check (equal? (semantic-label-text (segment-label seg "arbitrary text")) "arbitrary text") "authored text rewritten")))
  (cons "bad label text, units, precision and degenerate angles fail"
   (lambda ()
    (for ([thunk (list (lambda () (point-label A "")) (lambda () (segment-label s "x\ny"))
                       (lambda () (length-label s #:precision -1)) (lambda () (length-label s #:precision 13))
                       (lambda () (length-label s "a" #:unit "cm"))
                       (lambda () (length-label s #:unit "cm\n"))
                       (lambda () (angle-label (angle-spec B A A)))
                       (lambda () (angle-label (angle-spec (point -1 0) (point 0 0) (point 1 0)))) )])
      (fails thunk))))
  (cons "typed helper inputs and multi-results carry transforms and labels"
   (lambda ()
    (define t (construction->timeline typed-helper-demo))
    (define env (geometry-realization-values (geometry-timeline-realization t)))
    (check (semantic-label? (hash-ref env 'caption)) "label helper result lost")
    (check (equal? (semantic-label-text (hash-ref env 'caption)) "a′") "helper text lost")
    (check (equal? (hash-ref env 'image) (segment (point -2 2) (point 1 2))) "helper transform")
    (define plan (prepare-geometry-annotations t))
    (check (hash-has-key? (annotation-plan-labels plan) 'caption) "helper label layout")
    (near (point-x (hash-ref (annotation-plan-labels plan) 'caption)) -0.8)))
  (cons "nondrawable values do not create visual events"
   (lambda ()
    (define p (compile '((given [O (point 0 0)]) (step [v (vector 1 2)] [t (translation v)] [word "a"]))))
    (define t (construction->timeline p))
    (check (null? (geometry-timeline-events t)) "value binding added a render event")
    (check (equal? (construction-visible-ids p) '(O)) "values became visible")))
  (cons "DSL direct transforms match reusable transforms"
   (lambda ()
    (define p
      (compile '((given [A (point 1 2)] [O (point 0 0)] [l (line O (point 1 1))])
                 (step [x (translate A (vector 3 -1))] [y (transform (translation (vector 3 -1)) A)]
                       [r (rotate A O (degrees -30))] [s (transform (rotation O (degrees -30)) A)]
                       [m (reflect A l)] [n (transform (reflection l) A)]
                       [u (dilate A O -2)] [v (transform (dilation O -2) A)]))))
    (define r (realize-construction p))
    (for ([pair '((x y) (r s) (m n) (u v))]) (same (construction-ref r (car pair)) (construction-ref r (cadr pair))))))
  (cons "compiler rejects wrong transformation and label types and options"
   (lambda ()
    (for ([expression '((translate A B) (reflect A s) (rotation s 1) (rotate A B "90")
                        (transform A B) (dilation A 0) (dilate A B 0)
                        (length-label A) (point-label s "S") (point-label A)
                        (angle-label s "α") (segment-label s 5)
                        (length-label s #:precision 2 #:precision 1)
                        (length-label s #:unknown 1) (segment-label s "x" #:arc? #t)
                        (length-label s #:precision 0.5) (length-label s "a" #:unit "cm")
                        (angle-label (angle A B C) #:arc? "yes"))])
     (fails (lambda () (compile `((given [A (point 0 0)] [B (point 3 0)] [C (point 1 2)] [s (segment A B)])
                                   (step [bad ,expression]))))))))
  (cons "semantic labels have independent visibility and no duplicate auto names by magic"
   (lambda ()
    (define t (construction->timeline
      (compile '((given [A (point 0 0)] [B (point 3 0)] [s (segment A B)])
                 (initially (hide-label A))
                 (step [tag (point-label A "A′")] [dim (length-label s "a")])
                 (step (hide s)) (step (hide-label tag)) (step (show-label tag))))))
    (define final (geometry-timeline-final t))
    (check (not (presentation-shown? (hash-ref final 's))) "source still visible")
    (check (presentation-shown? (hash-ref final 'dim)) "label incorrectly cascaded")
    (check (presentation-label? (hash-ref final 'tag)) "show-label ignored")
    (check (not (presentation-label? (hash-ref final 'A))) "automatic name silently restored")))
  (cons "semantic label placement, offsets, pins and theme inheritance"
   (lambda ()
    (define p (compile '((given [A (point -2 0)] [B (point 2 0)] [s (segment A B)])
                         (layout (label-position d 0.4) (label-side d 'above)
                                 (label-offset tag (point -0.2 0.4)))
                         (initially (hide-label A))
                         (step [d (length-label s "a")] [tag (point-label A "A′")]))))
    (define t (construction->timeline p)) (define plan (prepare-geometry-annotations t))
    (near (point-x (hash-ref (annotation-plan-labels plan) 'd)) -0.4)
    (check (> (point-y (hash-ref (annotation-plan-labels plan) 'd)) 0) "dimension on wrong side")
    (same (hash-ref (annotation-plan-labels plan) 'tag) (point -2.2 0.4))
    (same (hash-ref (annotation-plan-labels (prepare-geometry-annotations t #:labels (hash 'tag (point -1 1)))) 'tag) (point -1 1))
    (check (equal? plan (prepare-geometry-annotations t)) "layout nondeterministic")
    (define theme (geometry-theme (label [font-size 0.31])
                     (semantic-label [offset 0.2]) (length-label (label [font-style italic]))))
    (define style (resolve-geometry-style theme 'length-label 'normal))
    (near (hash-ref style 'font-size) 0.31) (near (hash-ref style 'offset) 0.2)
    (check (eq? (hash-ref style 'font-style) 'italic) "kind theme not applied")))
  (cons "triangle side labels can be constrained outside the opposite vertex"
   (lambda ()
    (define p
      (compile '((given [A (point 0 2)] [B (point -2 0)] [C (point 2 0)])
                 (layout (label-outside-of a A) (label-outside-of b B)
                         (label-outside-of c C))
                 (step [BC (segment B C)] [CA (segment C A)] [AB (segment A B)]
                       [a (length-label BC "a")] [b (length-label CA "b")]
                       [c (length-label AB "c")]))))
    (define t (construction->timeline p))
    (define plan (prepare-geometry-annotations t))
    (define env (geometry-realization-values (geometry-timeline-realization t)))
    (define (opposite-side? label-id segment-id vertex-id)
      (define pos (hash-ref (annotation-plan-labels plan) label-id))
      (define seg (hash-ref env segment-id))
      (define vertex (hash-ref env vertex-id))
      (define u (point- (segment-b seg) (segment-a seg)))
      (< (* (cross u (point- pos (segment-a seg)))
            (cross u (point- vertex (segment-a seg)))) 0))
    (check (opposite-side? 'a 'BC 'A) "a is not outside BC")
    (check (opposite-side? 'b 'CA 'B) "b is not outside CA")
    (check (opposite-side? 'c 'AB 'C) "c is not outside AB")
    (fails (lambda ()
             (prepare-geometry-annotations
              (construction->timeline
               (compile '((given [A (point 0 0)] [B (point 2 0)] [C (point 1 0)])
                          (layout (label-outside-of d C))
                          (step [AB (segment A B)] [d (length-label AB "d")]))))))
           #rx"supporting line")
    (fails (lambda ()
             (compile '((given [A (point 0 0)] [B (point 2 0)])
                        (layout (label-outside-of A B)))))
           #rx"Label")))
  (cons "label-outside-of follows helper result aliases and caller vertices"
   (lambda ()
    (define t (construction->timeline outside-helper-demo))
    (define plan (prepare-geometry-annotations t))
    (define env (geometry-realization-values (geometry-timeline-realization t)))
    (define pos (hash-ref (annotation-plan-labels plan) 'side-name))
    (define seg (semantic-label-target (hash-ref env 'side-name)))
    (define vertex (hash-ref env 'P))
    (define u (point- (segment-b seg) (segment-a seg)))
    (check (< (* (cross u (point- pos (segment-a seg)))
                 (cross u (point- vertex (segment-a seg)))) 0)
           "helper outside hint lost")))
  (cons "angle labels stay in their angular sectors, with optional arcs"
   (lambda ()
    (for ([arc? '(#t #f)])
      (define p (compile `((given [A (point 2 0)] [B (point 0 0)] [C (point 1 2)])
                           (initially (hide-label A B C))
                           (step [BA (segment B A)] [BC (segment B C)]
                                 [q (angle-label (angle A B C) "α" #:arc? ,arc?)]))))
      (define t (construction->timeline p)) (define plan (prepare-geometry-annotations t))
      (define pos (hash-ref (annotation-plan-labels plan) 'q))
      (check (and (> (point-x pos) 0) (> (point-y pos) 0)
                  (< (/ (point-y pos) (point-x pos)) 2)) "label outside angle" pos)
      (check (equal? (hash-has-key? (annotation-plan-marker-placements plan) 'q) arc?) "arc placement mismatch"))))
  (cons "computed label targets participate in view fitting and review snapshots"
   (lambda ()
    (define t (construction->timeline
      (compile '((given [A (point 0 0)])
                 (step [d (length-label (segment (point 4 0) (point 8 0)) "d")])))))
    (check (semantic-label? (construction-ref (geometry-timeline-realization t) 'd)) "no label")
    (check (member (point 6 0) (realization-anchor-points (geometry-timeline-realization t))) "missing anchor")
    (define plan (make-geometry-review-plan t))
    (check (= (length (geometry-review-samples plan)) 3) "review not a triplet")
    (for ([sample (geometry-review-samples plan)])
      (check (hash-has-key? (geometry-frame-appearances (geometry-review-sample-frame sample)) 'd) "review lost label"))))))

(define-runtime-path examples "../examples")
(define example-groups
 (for*/list ([name '("transformations" "semantic-labels" "gallery")] [mode '(light dark)])
  (cons (format "example ~a / ~a: realization, annotations, review, repeat sampling" name mode)
   (lambda ()
     (define t ((dynamic-require (build-path examples (string-append name ".rkt")) 'make-demo-timeline) #:theme-mode mode))
     (define plan (prepare-geometry-annotations t))
     (check (positive? (geometry-timeline-duration t)) "empty example")
     (check (positive? (hash-count (annotation-plan-texts plan))) "no labels")
     (check (null? (annotation-plan-warnings plan)) "estimated annotation conflict in new demonstration" (annotation-plan-warnings plan))
     (define reviews (geometry-review-samples (make-geometry-review-plan t)))
     (check (positive? (length reviews)) "no review frames")
     (for ([sample reviews])
       (define time (geometry-review-sample-time sample))
       (define frame (sample-geometry-timeline t time))
       (sample-geometry-timeline t 0)
       (check (equal? frame (sample-geometry-timeline t time)) "history-dependent sampling"))
     (check (equal? plan (prepare-geometry-annotations t)) "history-dependent annotations")))))

(define transform-label-check-groups (append transformation-groups semantic-groups example-groups))
(define (run-transform-label-checks)
  (define counter (box 0))
  (for ([g transform-label-check-groups])
    (printf "~a ... " (car g)) (flush-output)
    (parameterize ([context (car g)] [count counter]) ((cdr g)))
    (displayln "ok"))
  (printf "~a groups, ~a checks passed.\n" (length transform-label-check-groups) (unbox counter)))
(module+ main (run-transform-label-checks))
